docs:第10回web研資料
saitamau-maximum/blog pull request #104
Opened 2024-07-13 21:01 UTC by batora9

「発展的なWebアプリを作る(1)」から内容を変更しました

2024-07-14 03:48 UTC, a01sa01to requested changes

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +UXとは、ユーザーがサービスを利用する際の全体的な体験のことを指します。例えば、サイトの読み込み速度や、ページ遷移のしやすさ、情報の探しやすさなどに当たり、実体を持たないもののことを指します。
直感的には UI ⊂ UX なんだけど、この文章だと UI ∩ UX = ∅ の印象を受けるなぁ

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +![UI,UX,CXの関係](https://shiftasia.com/wp-content/uploads/2022/04/uiuxcx_01-1.png)
外部の画像を直で読み込ませるのはやめましょう (リンク先がなくなったり変な画像に差し替えられたりする可能性があるので)

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +## UIについて
UI, UX, CX についてを h3 にする？

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +
なんか、「XX で採用されており、多くのWebサイトやアプリケーションでも採用されています。」がめちゃくちゃ繰り返されているのでうーんといったかんじ

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +Googleが公開している「Google Icons」というアイコンのカタログがあるので、こちらを使ってみましょう。
Google Icons ではないな (よくタイトルを見ましょう、 AI に丸投げしているのがバレます)

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +
Maximum でも使ってますみたいなことを入れるといいかも

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +<https://www.figma.com/downloads/>
ここはリンクカードにする必要はなさそう？

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +### Material-UI
Material UI (ハイフンなし) が正式表記っぽい？

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +UIライブラリを使うことで、デザインを簡単に組み立てられることができますが、完成されたデザインを使うことになるため、他人とデザインが被ることがあります。オリジナリティを出すためには、やはりライブラリに頼らずにCSSを書くことが大切だと思います。
ちなみに Maximum UI もあったりするので見てみてねを入れる？

2024-07-14 03:48 UTC, a01sa01to commented on public/images/blog/2024/webken-10/styled-todo-app.png
周りの空白が気になるのでトリミングしよう

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +UXとは、ユーザーがサービスを利用する際の全体的な体験のことを指します。例えば、サイトの読み込み速度や、ページ遷移のしやすさ、情報の探しやすさなどに当たり、実体を持たないもののことを指します。
実際下の「UI, UX, CX の関係」の図では UI ⊂ UX だしなぁ

2024-07-14 03:48 UTC, a01sa01to commented on blog/2024/webken/10.md
> +UXとは、ユーザーがサービスを利用する際の全体的な体験のことを指します。例えば、サイトの読み込み速度や、ページ遷移のしやすさ、情報の探しやすさなどに当たり、実体を持たないもののことを指します。
実際下の「UI, UX, CX の関係」の図では UI ⊂ UX だし

2024-07-15 04:02 UTC, batora9 commented on blog/2024/webken/10.md
> +UIライブラリを使うことで、デザインを簡単に組み立てられることができますが、完成されたデザインを使うことになるため、他人とデザインが被ることがあります。オリジナリティを出すためには、やはりライブラリに頼らずにCSSを書くことが大切だと思います。
いれます

2024-07-15 04:08 UTC, yukikamome316 approved these changes

2024-07-15 04:17 UTC, batora9 commented on blog/2024/webken/10.md
> +UIライブラリを使うことで、デザインを簡単に組み立てられることができますが、完成されたデザインを使うことになるため、他人とデザインが被ることがあります。オリジナリティを出すためには、やはりライブラリに頼らずにCSSを書くことが大切だと思います。
Maximum UIってFigmaのTeam projectにあるものですよね？
「見てみてね」→「Figmaのアカウント&招待が必要」になりますよね？

2024-07-15 04:20 UTC, a01sa01to commented on blog/2024/webken/10.md
> +UIライブラリを使うことで、デザインを簡単に組み立てられることができますが、完成されたデザインを使うことになるため、他人とデザインが被ることがあります。オリジナリティを出すためには、やはりライブラリに頼らずにCSSを書くことが大切だと思います。
https://github.com/saitamau-maximum/ui

2024-07-15 04:22 UTC, batora9 commented on blog/2024/webken/10.md
> +UIライブラリを使うことで、デザインを簡単に組み立てられることができますが、完成されたデザインを使うことになるため、他人とデザインが被ることがあります。オリジナリティを出すためには、やはりライブラリに頼らずにCSSを書くことが大切だと思います。
ありがとうございます

2024-07-15 04:57 UTC, sor4chi requested changes

2024-07-15 04:57 UTC, sor4chi commented on blog/2024/webken/10.md
> +
ここら辺画像入れれないかな？

2024-07-15 04:57 UTC, sor4chi commented on blog/2024/webken/10.md
> +
websiteのUIとかでもいいよ

2024-07-15 04:57 UTC, sor4chi commented on blog/2024/webken/10.md
> +デザインシステムを導入することで、例えばサイトの色調を緑に統一したり、ボタンのデザインを角丸に統一するなど、デザインの一貫性を保つことで、ユーザーにとって見やすく使いやすいWebサイトを作ることができます。
```suggestion
デザインシステムを導入することで、例えばサイトの色調を緑に統一したり、ボタンのデザインを角丸に統一するなど、デザインの一貫性を保つことができ、ユーザーにとっての見やすさを仕組みである程度担保できます。
```

2024-07-15 04:57 UTC, sor4chi commented on blog/2024/webken/10.md
> +アクセントとして目立たせたい「セカンダリカラー」を決めます。この色は、プライマリカラーとは**異なる相性の良い色**(500番前後)を選びましょう。
色調についてはアクセシビリティに触れるといいかも

https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum

W3Cで定められているように、色覚異常者に対するバリアフリーなカラーリングを提供するために背景色と文字色の組み合わせのコントラストを一定以上にしようという決まりがあって、Chromeの拡張機能やオンラインサービスでいつでも調べれられるようになっている。

https://accessibleweb.com/color-contrast-checker/

2024-07-15 04:57 UTC, sor4chi commented on blog/2024/webken/10.md
> +10px以下のフォントサイズは読みにくく、さらに7px以下だとモニター上で文字がつぶれてしまうので、避けるようにしましょう。
フォントサイズは使うフォントによっても微妙に変わってきますみたいな補足が欲しい

2024-07-15 04:57 UTC, sor4chi commented on blog/2024/webken/10.md
> +これを使うことで、~~面倒な~~CSSを書かなくても簡単にデザインを組み立てることができます。
ProsとConsをちゃんと明記した方がいいと思ってて

Pros:
- 迅速に開発できる
- 有名なライブラリだと使用例やチュートリアルなどが豊富
- デザインが予め決められているのでデザインの知識がそれほど必要ない

Cons:
- 独自のデザインを入れようとすると難しい
  - そもそも外部からスタイルが当てられない前提でUIライブラリは作られている
- サイト全体がそのUIライブラリに依存してしまうため、置き換えやバージョンアップなどの際に大変

を書いてほしい

2024-07-15 06:24 UTC, sor4chi approved these changes

2024-07-15 07:41 UTC, a01sa01to approved these changes

2024-07-15 07:42 UTC, merged