docs:夏休みに向けて
saitamau-maximum/blog pull request #106
Opened 2024-07-18 05:29 UTC by batora9

2024-07-19 16:17 UTC, shigekk commented
みんなで参加登録したいので、AtCoderの項目にリンク貼ってほしいです
よろしく
https://atcoder.jp/contests/abc366

2024-07-20 02:04 UTC, a01sa01to requested changes

2024-07-20 02:04 UTC, a01sa01to commented on blog/2024/webken/11.md
> +<https://youtube.com/playlist?list=PLIy7lkgHtMGeSwpMCGR6Zy1KXmumqn6rn&feature=shared>
これ公開していいのかな (一応限定公開という扱いにはなっているので)
もし公開するんだったら YouTube 側も公開設定にしちゃっていい気がしていて

2024-07-20 02:04 UTC, a01sa01to commented on blog/2024/webken/11.md
> +- GitHubを使って共同開発
```suggestion
- GitHubを使った共同開発
```

2024-07-20 02:04 UTC, a01sa01to commented on blog/2024/webken/11.md
> +例えば、講習会で扱ってない技術に触れる、共同開発をする、ABCなどのコンテストに積極的に参加する、CTFに挑戦する、インターンに参加するなどなど
FE, AP とかの資格勉強をする (今思いついた)

2024-07-20 02:04 UTC, a01sa01to commented on blog/2024/webken/11.md
> +もし夏休みの間に作りたいものが決まらなったらポートフォリオに挑戦してみるのもいいかもしれません。
```suggestion
もし夏休みの間に作りたいものが決まらなかったらポートフォリオに挑戦してみるのもいいかもしれません。
```

2024-07-20 02:04 UTC, a01sa01to commented on blog/2024/webken/11.md
> +前期の入門講習会では、主に基本的なアルゴリズムについて学び、実践講習会ではICPC予選の問題扱いました。
```suggestion
前期の入門講習会では、主に基本的なアルゴリズムについて学び、実践講習会ではICPC予選の問題を扱いました。
```

2024-07-20 02:04 UTC, a01sa01to commented on blog/2024/webken/11.md
> +10/19 13:00-14:40
夏休み中じゃないので、エントリーして練習しよう！みたいな形がいいかも

2024-07-20 06:02 UTC, sor4chi requested changes

2024-07-20 06:02 UTC, sor4chi commented on blog/2024/webken/11.md
> +ポートフォリオを作ることで、Webの知識が増えるだけでなく、ゼロからデザインを考えたり、ブログ記事を積極的に書く習慣ができたり、自分の作ったものを公開することでアピールになったりします。
+ 実際、エンジニアは会社の書類選考なのでポートフォリオの提出を求められることがよくあります

2024-07-20 06:02 UTC, sor4chi commented on blog/2024/webken/11.md
> +**とにかくアウトプットが大事です。** 学んだことを実際に使ってみることで理解が深まったり、新しい知識が身につくこともあります。プログラミングを効率よく学ぶためには、「何かを作りたい！」という作りたい駆動でやるとうまくいきます。
ditto

2024-07-20 06:55 UTC, closed without merging