累積和といもす法
saitamau-maximum/blog pull request #107
Opened 2024-10-03 02:43 UTC by LLstream

2024-10-03 06:41 UTC, yukikamome316 commented
@LLstream 
資料作成ありがとう！
これからは最初にDraft PRを立てて、資料が完成してレビューを受けたい状態になってから Draft を外して Review requests 飛ばすようにしてほしい！

2024-10-03 07:19 UTC, LLstream commented
@yukikamome316 Draftの存在忘れてました…気を付けます

2024-10-07 04:04 UTC, a01sa01to requested changes
プレビュー (https://feat-intro-course-10.blog-eyq.pages.dev/blog/2024/intro-course/10/) 見ながらやってみて！

2024-10-07 04:04 UTC, a01sa01to commented on blog/2024/intro-course/10.md
> +具体的には更新範囲の境界部分のみを変更し、最終的に累積和を取ることによって正しい答えを得る方法です。
Markdown の blockquote をつかおう
```suggestion
> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。(<https://imoz.jp/algorithms/imos_method.html>)  

具体的には更新範囲の境界部分のみを変更し、最終的に累積和を取ることによって正しい答えを得る方法です。
```

2024-10-07 04:04 UTC, a01sa01to commented on blog/2024/intro-course/10.md
> +    vector<long long> s(n), t(n), p(n),check(2*10*10*10*10*10);
`2*10*...`、どうしてこうなった...
```suggestion
    vector<long long> s(n), t(n), p(n), check(200000);
```

2024-10-07 04:04 UTC, a01sa01to commented on blog/2024/intro-course/10.md
> +しかし、`ti-si`は最大で$2*10^5$であるので計算量は最大で$4*10^10$となり、TLEしてしまいます。
```suggestion
しかし、`ti-si`は最大で$2 \times 10^5$であるので計算量は最大で$4 \times 10^{10}$となり、TLEしてしまいます。
```

2024-10-07 04:04 UTC, a01sa01to commented on blog/2024/intro-course/10.md
> +    vector<long long> s(n), t(n), p(n), check(2*10*10*10*10*10+1);
ここも

2024-10-07 10:52 UTC, a01sa01to commented on blog/2024/intro-course/10.md
> +    vector<long long> s(n), t(n), p(n), check(200000);
@LLstream なおってなさそう

2024-10-07 16:37 UTC, LLstream commented on blog/2024/intro-course/10.md
> +### 解説
明日授業中にやります

2024-10-07 16:47 UTC, yukikamome316 requested changes

2024-10-07 16:47 UTC, yukikamome316 commented on blog/2024/intro-course/10.md
> +> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。(<https://imoz.jp/algorithms/imos_method.html>)
```suggestion
> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。
引用元: <https://imoz.jp/algorithms/imos_method.html>
```

こっちの方がスマホで描画崩れしないし自然だと思う

2024-10-07 16:47 UTC, yukikamome316 commented on blog/2024/intro-course/10.md
> +> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。(<https://imoz.jp/algorithms/imos_method.html>)
```suggestion
> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。
引用元: <https://imoz.jp/algorithms/imos_method.html>
```

こっちの方がスマホで描画崩れしないし自然だと思う

2024-10-07 16:47 UTC, yukikamome316 commented on blog/2024/intro-course/10.md
> +> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。(<https://imoz.jp/algorithms/imos_method.html>)
```suggestion
> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。
引用元: <https://imoz.jp/algorithms/imos_method.html>
```

こっちの方がスマホで描画崩れしないし自然だと思う

2024-10-08 07:06 UTC, hana-rs submitted a review, later dismissed

2024-10-08 07:08 UTC, yukikamome316 requested changes

2024-10-08 07:08 UTC, yukikamome316 commented on blog/2024/intro-course/10.md
> +引用元: <https://imoz.jp/algorithms/imos_method.html>
```suggestion
> いもす法とは、累積和のアルゴリズムを多次元，多次数に拡張したものです。  

引用元: <https://imoz.jp/algorithms/imos_method.html>  
```

2024-10-08 07:14 UTC, a01sa01to approved these changes

2024-10-08 07:27 UTC, hana-rs approved these changes

2024-10-08 08:37 UTC, yukikamome316 approved these changes

2024-10-08 08:40 UTC, merged