feat: 入門講習会第５回の資料を作成
saitamau-maximum/blog pull request #14
Opened 2023-05-21 15:00 UTC by kasa021

計算量についてわかりやすく理解できるように書いたつもり...
bit演算については簡素にして、bit全探索は例題を交えながら理解できるように書きました
bitsetはおまけ程度にしました。
全体の量が多すぎるなどがあれば言ってください。

レビューお願いします。

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +  - n(n+1)/2 を計算する : 3 回の計算を行う
等差数列の和の公式から、とか書いたほうがいいかも
数式で \frac{n(n+1)}{2}

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +このプログラムでは、for 文を n 回繰り返しているので、計算回数はおおよそ n 回になります。この時時間計算量はオーダー記法を用いて`O(n)`と表します。このように、計算量を表すときには、計算回数ではなく、計算回数のオーダーを表します。
このとき、ひらがなにしよう or 読点を打とう

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +$O(1) < O(logN) < O(N) < O(NlogN) < O(N^2) < O(2^N) < O(N!)$
log は \log と書くと斜体にならない

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +このコードは$N$を$2$で割り続けているので、$O(logN)$であらわされます。
説明難しいよね、$N (\frac{1}{2})^x = 1$ みたいな説明は必要かも

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +計算量の$log$は底はなんでもいいです。今回は、$log_2(N)$になります
「底の変換公式より、定数とみなせます」があると

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +基本的には、$10^8$~$10^9$あたりまでは許されます。
1秒あたり

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +| $N<10^{14}$ |      $O(N)$      |      素数判定      |
\sqrt{N}

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +|  それ以上   |    $O(logN)$     |      二分探索      |
O(1) も書く…？

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +AtCoder の問題では、`実行時間制限`、`メモリ制限`があるので計算量をよく考えます。
AtCoder に限らず

` で囲わず「」にする

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +`x<<n`と書いたとき、$2^n$ を掛けることと同じです。
「$x$ に」 $2^n$ を掛けることと同じ

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +`x>>n`と書いたとき、$2^n$ を割ることと同じです。
$2^n$ 「で」割る

ただし、小数点以下は切り捨てです

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +
「NOTはないです」をいれる？

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +
「bool の AND, OR と区別しましょう」
特に、この bit ごとの演算は「bitwise 〇〇」と呼ぶことがあります

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +符号あり整数型の場合(int,long long)、最上位 bit は符号を表すので、bit 演算を行うときは、符号なし整数型(unsigned int,unsigned long long)を使うようにしましょう。
符号を表すので、想定外の処理が起こることがあります。演算をするときは気をつけて演算をするか、符号なしか後で説明するbitsetを使いましょう

みたいな感じがいいかも

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +$1,2,4$の中から自由に数字を選んでいくつの数字を作ることができるか。一つも選ばないこともできる。
数字の作り方は足し算？
1つも選ばないときの処理

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +3 つのこの数字を選ぶ、選ばないの 2 パターンを bit で表す。$0$から$2^n-1$まで今回は$2^3-1$まで調べる。
0から2ⁿ-1まで (今回は〜) とするといいかも

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +- 問題の言っていることは、選び出した集合の中に$1$から$N$までの数字が含まれていますかということ。
数字が「すべて」含まれていますか？ということ

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +        if ((int)s.size() == n)
なんでこれでいいのかについての説明があるといいかも

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +- bitsetは、ビット演算が高速に行える。
この言い方は微妙 (なくしてもいいかも…？)

2023-05-22 00:27 UTC, a01sa01to commented on blog/intro-course-5.md
> +bitset<長さ> 変数名;
長さは定数である必要があることに注意してください。すなわち、`bitset<n>` のような書き方はできません

2023-05-22 00:27 UTC, a01sa01to commented
めちゃくちゃコメントしてしまった…なんか申し訳ない

2023-05-22 03:21 UTC, kasa021 commented on blog/intro-course-5.md
> +|  それ以上   |    $O(logN)$     |      二分探索      |
追加しといた

2023-05-22 03:28 UTC, kasa021 commented on blog/intro-course-5.md
> +
一応ないって書いておくか。

2023-05-22 03:32 UTC, kasa021 commented on blog/intro-course-5.md
> +
bitwiseという言葉は知りませんでした....

2023-05-22 03:51 UTC, yukikamome316 requested changes

2023-05-22 03:51 UTC, yukikamome316 commented on blog/intro-course-5.md
> +表せます。この式の両辺を$\log$をとると、$x=log_2(N)$となります。
`$x = \log_2 N$`とすると
$x = \log_2 N$
になります

2023-05-22 03:51 UTC, yukikamome316 commented on blog/intro-course-5.md
> +計算量の$\log$は底はなんでもいいです。底の変換公式より、$log_a(N)=\frac{log_b(N)}{log_b(a)}$なので、定数とみなせます。
$\log_a N =\frac{\log_b N}{\log_b a}$

2023-05-22 03:51 UTC, yukikamome316 commented on blog/intro-course-5.md
> +|  $N<=10^5$  |    $O(NlogN)$    |       ソート       |
$O(N\log N)$

2023-05-22 03:55 UTC, a01sa01to commented
ところどころ数式になってない部分があるので直してほしい
たぶんほとんどが前後に空白を入れれば直ると思う
あと \log の後は空白いれよう

コメントするとめちゃくちゃ長くなっちゃうけど、以下プレビューを見ながらやってみて
https://github.com/saitamau-maximum/blog/blob/feat/intro-course-5/blog/intro-course-5.md
もしかしたら Web Editor がプレビューもあって直しやすいかも

2023-05-22 05:41 UTC, a01sa01to commented
ふと思ったんだけど、この計算量はいくらでしょう？とかってあったほうがいいのかな
割と重要なので

```cpp
int main() {
  int n; cin >> n;
  vector<int> a(n);
  for (int i = 0; i < n; i++) cin >> a.at(i);
  sort(a.begin(), a.end());  // N log N
  for (int i = 0; i < n; i++) cout << a.at(i) << " \n"[i == n - 1];
  return 0;
}
```

2023-05-22 08:32 UTC, takashin9 commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
¥dfracって使える？使えたらそのほうが見栄えいいかも

2023-05-22 08:38 UTC, takashin9 commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
¥mathrm{¥log}Nじゃなくても¥log Nで行けるよ（logとNの間スペース空けてね）

2023-05-22 08:49 UTC, takashin9 commented on blog/intro-course-5.md
> +  - 等差数列の公式を用いて $\frac{n(n+1)}{2}$ を計算する : 3 回の計算を行う
ここも¥dfrac使えたら使ったほうが見栄えいい

2023-05-22 08:51 UTC, takashin9 commented on blog/intro-course-5.md
> +6. $O(Nlog(N))$
¥log

2023-05-22 09:48 UTC, kasa021 commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
> ふと思ったんだけど、この計算量はいくらでしょう？とかってあったほうがいいのかな 割と重要なので
> 
> ```c++
> int main() {
>   int n; cin >> n;
>   vector<int> a(n);
>   for (int i = 0; i < n; i++) cin >> a.at(i);
>   sort(a.begin(), a.end());  // N log N
>   for (int i = 0; i < n; i++) cout << a.at(i) << " \n"[i == n - 1];
>   return 0;
> }
> ```

例題で計算量見積もるやつあるからいいかなって思ったんだけど、ほしい？

2023-05-22 09:49 UTC, kasa021 commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
ごめん変なところにリプライしちゃった。使い方わかってなくて.....
すんません

2023-05-22 14:25 UTC, a01sa01to commented
https://github.com/saitamau-maximum/blog/pull/14/commits/39291ddbd660971500f5c5227dfc74f50e5b48d9

> この言い方は微妙 (なくしてもいいかも…？)

は「bit演算が高速」の部分で、「任意の長さを扱える」のほうではないです！めちゃくちゃ申し訳ない！！

2023-05-22 14:35 UTC, a01sa01to commented on blog/intro-course-5.md
> +| $N<10^{14}$ |      $O(\sqrt{N})$      |      素数判定      |
<= は `\le` とすることで $\le$ になる

2023-05-22 14:36 UTC, kasa021 commented on blog/intro-course-5.md
> +| $N<10^{14}$ |      $O(\sqrt{N})$      |      素数判定      |
あざす

2023-05-22 14:37 UTC, a01sa01to commented on blog/intro-course-5.md
> +authors: "kasa021"
array にする (build check エラーの原因はたぶんこれ)

`authors: ["kasa021"]`

2023-05-22 14:38 UTC, kasa021 commented on blog/intro-course-5.md
> +authors: "kasa021"
なるほど

2023-05-22 14:38 UTC, a01sa01to commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
frac は dfrac にしたほうが見栄えがいいらしい

2023-05-22 14:39 UTC, kasa021 commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
修正し忘れてました....
$N (\frac{1}{2})^x = 1$これは\fracのままでいい？これは\fracの方が見た目よかった

2023-05-22 14:40 UTC, kasa021 commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
$N (\dfrac{1}{2})^x = 1$

2023-05-22 14:45 UTC, kasa021 commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
###　コードを見てみようのところに追加すればいい感じ？

2023-05-22 14:46 UTC, kasa021 commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
89行目からのとこ

2023-05-22 14:48 UTC, kasa021 commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
俺今回sortの計算量書いてないよ

2023-05-22 23:13 UTC, yukikamome316 commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
$N \Bigl( \dfrac{1}{2} \Bigr) ^x = 1$

2023-05-23 00:36 UTC, a01sa01to commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
あーうん、 `### コードを見てみよう` に追加してほしい
「sort より下のほうがいい」っていうのは、例のコードは、最初に挙げた sort で $O(N \log N)$ よりも、次に挙げたやつ (関数を呼び出して $O(NM)$ ) がよさそうっていう意図でした

2023-05-23 00:38 UTC, a01sa01to commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
$N \left( \dfrac{1}{2} \right) ^x = 1$

`$N \left( \dfrac{1}{2} \right) ^x = 1$`

2023-05-23 00:39 UTC, a01sa01to commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
うーん、おまかせします

2023-05-23 02:29 UTC, kasa021 commented on blog/intro-course-5.md
> +計算量の $\log$ は底はなんでもいいです。底の変換公式より、 $\log_a(N)=\frac{\log_b(N)}{\log_b(a)}$ なので、定数とみなせます。
提案ありがとう

2023-05-23 02:32 UTC, kasa021 commented on blog/intro-course-5.md
> +これは $O(N\mathrm{\log}N)$ です。 $\log(N)$ を $N$ 回繰り返しているので、 $N\mathrm{\log}N$ になります。
なるほど、理解した

2023-05-23 06:23 UTC, yukikamome316 approved these changes

2023-05-23 07:15 UTC, a01sa01to commented on blog/intro-course-5.md
> +  cin >> n >> m;
これ m 関係なかったね、申し訳ない

2023-05-23 07:17 UTC, merged