Feat/ogp
saitamau-maximum/blog pull request #28
Opened 2023-05-27 12:34 UTC by seiei-n

2023-05-27 12:56 UTC, sor4chi requested changes

2023-05-27 12:56 UTC, sor4chi commented on tsconfig.json
> +    "target": "es2017",
これ必要？

2023-05-30 09:36 UTC, a01sa01to submitted a review, later dismissed

2023-05-30 09:36 UTC, a01sa01to commented
@sor4chi

2023-05-30 09:56 UTC, sor4chi commented on src/lib/ogp.ts
> +const OGP_GENERATED_IMAGE_PATH = "images/ogp/generated/";
これ
https://github.com/saitamau-maximum/blog/blob/2d9bfb02bd6f8412606f7746f3c08b23870031aa/src/constants/url.ts#L1
に
```ts
export const ROUTE = {
  ...
  OGP_BASE_IMAGE_PATH: "images/ogp/base.png",
  OGP_DEFAULT_IMAGE_PATH: "images/ogp/default.png",
  OGP_GENERATED_IMAGE_DIR_PATH: "images/ogp/generated"
  OGP_DYNAMIC_IMAGE: (slug: string[]) => `${URL.OGP_GENERATED_IMAGE_DIR_PATH}/${slug.join("-")}.png`,
  ...
);
```
に定義して、それを呼ぶ形にして欲しい

さっきのブログをネストする改造でslugが`string`から`string[]`に変わってるので注意

2023-05-30 09:58 UTC, sor4chi commented on src/lib/ogp.ts
> +const MAX_TITLE_WIDTH = OGP_WIDTH - 160;
端から１文字分の余白をとってることを明示する感じ

2023-05-31 04:39 UTC, seiei-n commented
@sor4chi
おなしゃす

2023-05-31 06:56 UTC, sor4chi approved these changes
ありがとうLGTM

もしかしたらGithub Action上の日本語フォントの問題でOGPが崩れるかもしれないのでもし生成失敗したらキャッシュ消して再生成させよう

2023-05-31 11:15 UTC, merged