作業を開始しました
saitamau-maximum/blog pull request #69
Opened 2024-04-17 16:11 UTC by shigekk

2024-04-18 01:39 UTC, a01sa01to commented
作業途中なら Draft にすると良いです
![image](https://github.com/saitamau-maximum/blog/assets/26807394/58713a78-3e93-4385-b1f9-8a2884dd69c9)

2024-04-19 15:47 UTC, yukikamome316 commented on blog/2024/intro-course/1.md
> +title: "【第1回】競プロのための環境構築"
ブログ記事として公開しているのに、第？回の表記はいらない気がする...
今年度からはこれ消すのはどうかな？

2024-04-19 17:29 UTC, shigekk commented on blog/2024/intro-course/1.md
> +title: "【第1回】競プロのための環境構築"
後から見返した人が流れを追いやすい方が良いかと思ったんですが
何かいい方法はないですかね

2024-04-19 17:30 UTC, yukikamome316 requested changes
とりあえずこれだけお願いします！

2024-04-19 17:30 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +・Atcoderに登録
```suggestion
- コードを書くためのソフト VSCode の入手
- C++ をコンパイルするための `build-essential` のインストール  
- AtCoder に登録  
```

箇条書きには `-` (ハイフン) を用いるとよいです！

2024-04-19 17:30 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +Atcoderを利用しc++で競プロを始めるための準備として環境構築を行います．
```suggestion
AtCoderの登録と，C++で競プロを始めるため環境構築を行います．
``

2024-04-19 17:30 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +（※今回の境構築をしないとAtcoderを利用できないということでは無いです）
```suggestion
    - 今回の環境構築をしないとAtCoderを利用できないということでは無いです
```

2024-04-19 18:07 UTC, shigekk commented on blog/2024/intro-course/0.md
> +（※今回の境構築をしないとAtcoderを利用できないということでは無いです）
![スクリーンショット 2024-04-20 030559](https://github.com/saitamau-maximum/blog/assets/132898053/d1c30481-cf16-4cbc-b2ed-686c0f9c6f44)
こういう感じでいいですか

2024-04-19 18:10 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +（※今回の境構築をしないとAtcoderを利用できないということでは無いです）
markdownだから、※を使うのではなくて箇条書きのレベルを下げて詳細を書く方がいいかなーって思ったんだけど、直すかどうかは任せます！

後は大丈夫です！

2024-04-19 18:14 UTC, shigekk commented on blog/2024/intro-course/0.md
> +（※今回の境構築をしないとAtcoderを利用できないということでは無いです）
注意書きのニュアンスを持たせたかったので※でいきたいと思います
そもそもこの注意書きが要らないかもしれないですが

2024-04-20 06:58 UTC, batora9 requested changes

2024-04-20 06:58 UTC, batora9 commented on blog/2024/intro-course/0.md
> +### VSCodeのインストール
いきなりVSCodeと呼ばないでVisual Studio Codeと呼びましょう。「以下、VSCodeとする。」などの説明も加えましょう。

2024-04-20 06:58 UTC, batora9 commented on blog/2024/intro-course/0.md
> +/home/ユーザー名/maximum/kyopro/test.cpp　となるように
見やすいように
`/home/ユーザー名/maximum/kyopro/test.cpp`
こうかな

2024-04-20 07:01 UTC, batora9 commented
ブランチ名`feat/...`じゃなくて`docs/...`がいいのでは
まあこれは次回から

2024-04-20 07:31 UTC, yukikamome316 requested changes
図が分かりやすくていいね
あとは細かいところの修正をお願いしたい！

2024-04-20 07:31 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +cd /home/ユーザー名/maximum/kyopro
`kyopro` よりも `competition` のほうがいい気がする...？

それと、外部に提出するプログラムなので、 `~/maximum/competition` とするよりも、 `~/competition` とした方が分かりやすいかも！

2024-04-20 07:31 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +### AAPG4bの紹介
```suggestion
### APG4bの紹介
```

2024-04-20 07:43 UTC, shigekk commented on blog/2024/intro-course/0.md
> +cd /home/ユーザー名/maximum/kyopro
了解です！
ちなみに外部に提出するってどういうことですか

2024-04-20 07:45 UTC, yukikamome316 commented on blog/2024/intro-course/1.md
> +title: "【第1回】競プロのための環境構築"
そうだなー
private-websiteに載せるのはどうかな？
もしそうするならこちらで対応しておく！

2024-04-20 07:51 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +cd /home/ユーザー名/maximum/kyopro
Web研のコードは内部向けの練習用教材なので、 `maximum/webken` を作ってその中で作業するようにする予定

それに対して競プロのコードは、主にAtCoderに提出するファイルだからMaximum内部の練習用のコードというわけではなく、個人でもできると思うから `maximum/competition` とするのはどうなんだろう？って感じ

2024-04-20 10:24 UTC, batora9 commented
READMEみたら`feat/...`でいいのか

2024-04-20 11:10 UTC, a01sa01to requested changes

2024-04-20 11:10 UTC, a01sa01to commented on blog/2024/intro-course/0.md
> +以上で競プロを始めるため環境は整いました．
```suggestion
以上で競プロを始めるための環境は整いました．
```

2024-04-20 11:10 UTC, a01sa01to commented on blog/2024/intro-course/0.md
> +<https://atcoder.jp/register?lang=ja>
リンクちがうっぽい？

2024-04-20 14:34 UTC, sor4chi commented
@shigekk 
## Macの場合の環境構築, GCC環境の立て方
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
exec $SHELL -l
brew install gcc
gcc --version
g++ --version # この二つで出力にclangと指定されてれば変更の必要がある（下に続く）
ls /usr/local/bin | grep gcc # 6文字の行をコピー（正確には`^gcc\-\d+$`)
ln -s /usr/local/bin/[コピーしたやつ] /usr/local/bin/gcc # [コピーしたやつ] を適宜置き換えて実行
ls /usr/local/bin | grep g++ # 6文字の行をコピー（正確には`^g++\-\d+$`)
ln -s /usr/local/bin/[コピーしたやつ] /usr/local/bin/g++ # [コピーしたやつ] を適宜置き換えて実行
```

2024-04-20 16:04 UTC, yukikamome316 requested changes

2024-04-20 16:04 UTC, yukikamome316 commented on blog/2024/intro-course/0.md
> +g++ --version # この二つで出力にgccと出ていれば成功
\```zsh

のコードブロックにしなくて大丈夫？

2024-04-22 05:41 UTC, a01sa01to commented on blog/2024/intro-course/0.md
> +:::details[macOSの方へ]
これって対応する場所的に「build-essential のインストール」部分に書いたほうがいいんじゃないかなぁ

2024-04-22 05:44 UTC, a01sa01to commented on blog/2024/intro-course/0.md
> +chmod 777 ./test
個人的には
```suggestion
chmod +x ./test
```
が好みです (実行以外の余計な権限を付与しなくていいので)

2024-04-22 05:55 UTC, a01sa01to commented on blog/2024/intro-course/0.md
> +g++ --version # この二つで出力にgccと出ていれば成功
https://github.com/saitamau-maximum/blog/blob/ff610d0273582cc7caf27e488e7a454fac630d34/src/lib/markdown-server.ts#L1-L15
zsh 登録されてなさそう？

2024-04-22 05:56 UTC, sor4chi commented on blog/2024/intro-course/0.md
> +g++ --version # この二つで出力にgccと出ていれば成功
これそのうちmarkdown-processorに変えないとな...

2024-04-22 12:40 UTC, a01sa01to commented
一通り作業終わってレビューしていいよ～段階になったら Draft を外そう！
![image](https://github.com/saitamau-maximum/blog/assets/26807394/c0982563-ab25-4988-81a9-e9b88be3de28)

2024-04-22 23:15 UTC, sor4chi requested changes

2024-04-22 23:15 UTC, sor4chi commented on blog/2024/intro-course/0.md
> +g++ --version  # clangと出力された場合は、以下の手順で修正
```suggestion
g++ --version  # clangと出力された場合は、シンボリックリンクの設定に進む
```

2024-04-22 23:15 UTC, sor4chi commented on blog/2024/intro-course/0.md
> +GCCとG++のシンボリックリンクを設定します・
```suggestion
GCCとG++のシンボリックリンクを設定します
```

2024-04-22 23:15 UTC, sor4chi commented on blog/2024/intro-course/0.md
> +GCCとG++のバージョンを確認します・
```suggestion
GCCとG++のバージョンを確認します
```

2024-04-22 23:15 UTC, sor4chi commented on blog/2024/intro-course/0.md
> +:::
```suggestion
:::

```

2024-04-22 23:15 UTC, sor4chi commented on blog/2024/intro-course/0.md
> +```
```suggestion
もし①でgcc-10が出力されたら `/usr/local/bin/gcc-10` というように適宜変えてください

```bash
ls /usr/local/bin | grep gcc  # ①正しいバージョンを確認
ln -s /usr/local/bin/gcc-10 /usr/local/bin/gcc  # 適切なバージョンをリンク

ls /usr/local/bin | grep g++  # 同様に確認
ln -s /usr/local/bin/g++-10 /usr/local/bin/g++  # 適切なバージョンをリンク
```
```

2024-04-23 04:48 UTC, a01sa01to approved these changes

2024-04-23 05:55 UTC, yukikamome316 approved these changes

2024-04-23 07:14 UTC, merged