Web研第1回講義資料
saitamau-maximum/blog pull request #70
Opened 2024-04-20 10:36 UTC by batora9

所々、去年の内容をそっくり使った部分もあります。

2024-04-20 11:04 UTC, a01sa01to requested changes
:pray:

2024-04-20 11:04 UTC, a01sa01to commented on blog/2024/webken/1.md
> +    </body>
```suggestion
  <body>
    <h1>これは見出しです</h1>
    <p>これは段落です</p>
  </body>
```

2024-04-20 11:04 UTC, a01sa01to commented on blog/2024/webken/1.md
> +入れ子にした時、そのタグを囲むタグを親要素、そのタグに囲まれたタグを子要素と呼びます。
画像には兄弟があるけど説明しない？

2024-04-20 11:04 UTC, a01sa01to commented on blog/2024/webken/1.md
> +CSSはHTMLの見た目を変えるための言語です。CSSはHTMLのタグにスタイルを適用することができます。CSSはHTMLとは別のファイルに書くことができますが、今回はHTML内に`<style>`タグを使って書いてみましょう。
> CSSはHTMLのタグにスタイルを適用することができます

日本語に違和感？

2024-04-20 11:04 UTC, a01sa01to commented on blog/2024/webken/1.md
> +今回はWebの基礎を学び、HTMLとCSSを使ってWebページを作ってみました。次回はCSSの拡張とJavaScriptを使ってWebページを動かしてみましょう。
ただの興味なんだけど「CSS の拡張」って何を想定してる？

2024-04-20 11:07 UTC, a01sa01to commented on blog/2024/webken/1.md
> +next: "./2"
`next: "./2"` あるせいでビルド落ちてそう

2024-04-20 11:43 UTC, batora9 commented on blog/2024/webken/1.md
> +CSSはHTMLの見た目を変えるための言語です。CSSはHTMLのタグにスタイルを適用することができます。CSSはHTMLとは別のファイルに書くことができますが、今回はHTML内に`<style>`タグを使って書いてみましょう。
あーこれ実はCopilotです...

2024-04-20 11:43 UTC, batora9 commented on blog/2024/webken/1.md
> +今回はWebの基礎を学び、HTMLとCSSを使ってWebページを作ってみました。次回はCSSの拡張とJavaScriptを使ってWebページを動かしてみましょう。
CSSいっぱい書くよってことでした

2024-04-20 12:11 UTC, yukikamome316 commented on blog/2024/webken/1.md
> +title: "【第1回】Webのしくみ"
https://github.com/saitamau-maximum/blog/pull/69#discussion_r1572575319
これどう思う？

2024-04-20 13:03 UTC, a01sa01to commented on blog/2024/webken/1.md
> +今回はWebの基礎を学び、HTMLとCSSを使ってWebページを作ってみました。次回はCSSの拡張とJavaScriptを使ってWebページを動かしてみましょう。
:eyes:

2024-04-20 13:54 UTC, batora9 commented on blog/2024/webken/1.md
> +title: "【第1回】Webのしくみ"
あった方がいいと思います

2024-04-20 13:55 UTC, batora9 commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで、Webブラウザやスマホアプリなどを指します。
去年と同じ表現です

2024-04-20 14:07 UTC, a01sa01to commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで、Webブラウザやスマホアプリなどを指します。
なるほど 🤔

2024-04-20 14:08 UTC, a01sa01to commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで、Webブラウザやスマホアプリなどを指します。
なるほど 🤔 

@sor4chi どう思いますか

2024-04-20 14:19 UTC, batora9 commented on blog/2024/webken/1.md
> +入れ子にした時、そのタグを囲むタグを親要素、そのタグに囲まれたタグを子要素と呼びます。
この説明も去年と同じです。
説明をするとしたら口頭になると思います

2024-04-20 14:24 UTC, sor4chi commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで、Webブラウザやスマホアプリなどを指します。
えー去年僕が書いた表現なのでいいとしか思えない
逆にどういう表現がいいか提案して欲しいな

2024-04-20 14:25 UTC, sor4chi commented on blog/2024/webken/1.md
> +入れ子にした時、そのタグを囲むタグを親要素、そのタグに囲まれたタグを子要素と呼びます。
俺の画像使ってるのか...
時間なくて手書きにしたんだけどVSCodeのスクショとかの方がわかりやすくない？

2024-04-20 14:29 UTC, batora9 commented on blog/2024/webken/1.md
> +入れ子にした時、そのタグを囲むタグを親要素、そのタグに囲まれたタグを子要素と呼びます。
スクショを使ってもどうせ説明部分が手書きになってしまうのではないかと思ってそのまま使いました

2024-04-20 14:36 UTC, sor4chi commented on blog/2024/webken/1.md
> +入れ子にした時、そのタグを囲むタグを親要素、そのタグに囲まれたタグを子要素と呼びます。
Figmaという文明の力を知っているかね？

2024-04-20 14:38 UTC, batora9 commented on blog/2024/webken/1.md
> +入れ子にした時、そのタグを囲むタグを親要素、そのタグに囲まれたタグを子要素と呼びます。
そんな使い方するんですか...しらなかった

2024-04-20 15:10 UTC, a01sa01to commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで、Webブラウザやスマホアプリなどを指します。
クライアントはユーザーが直接触る部分とも限らないので、そういうのはどうなんだろっていう
例えば HTTP リクエストを送る側 (具体例として Web ブラウザやスマホアプリ) っていうのが個人的にはしっくりくるかなぁ

2024-04-20 16:03 UTC, sor4chi commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで、Webブラウザやスマホアプリなどを指します。
ここでもうプロトコルの話するの？w

2024-04-20 16:22 UTC, sor4chi requested changes

2024-04-20 16:22 UTC, sor4chi commented on blog/2024/webken/1.md
> +Webって何？と聞かれても年内の講義では語りつくせないほど幅広く曖昧なものです。Webは知らないといけない知識がとても多く、挫折しやすい分野でもあるため、講義内でも各自で開発する際にも分からないことがあったら、ぜひWeb研講師の@ばとら、@Tsuji、@sor4chi、@a01sa01toに聞いてみてください。いつでも歓迎します！
ここgithub idにしたさある

2024-04-20 16:22 UTC, sor4chi commented on blog/2024/webken/1.md
> +Web研は年間を通して主にフロントエンド・バックエンド・デザインの講義を行います。Webについて初心者の方も、経験者の方も講義＋各自の事後学習である程度の基礎的な知識や技術を身に着けることができると思います。また、Webを学習するにあたってわからないことがあったら、まずは自分で調べてみましょう。自分で調べることで、なにがわからないのか自分で把握することができたり、調べようと思ったこと以上に知識を
事後学習して欲しいけど、強制ではないので「＋各自の事後学習」は消しちゃってもいいかも

2024-04-20 16:22 UTC, sor4chi commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで、Webブラウザやスマホアプリなどを指します。
両方書こうか、厳密には〜みたいな感じで

2024-04-20 16:22 UTC, sor4chi commented on blog/2024/webken/1.md
> +Web研は年間を通して主にフロントエンド・バックエンド・デザインの講義を行います。Webについて初心者の方も、経験者の方も講義＋各自の事後学習である程度の基礎的な知識や技術を身に着けることができると思います。また、Webを学習するにあたってわからないことがあったら、まずは自分で調べてみましょう。自分で調べることで、なにがわからないのか自分で把握することができたり、調べようと思ったこと以上に知識を
`また、Webを学習するにあたってわからないことがあったら、まずは自分で調べてみましょう。自分で調べることで、なにがわからないのか自分で把握することができたり、調べようと思ったこと以上に知識を得ることができたり、調べる力がつくのではないかと思います。`
は 「Web研の使い方・学び方」という別のセクションにしたさある

これは例
```markdown
## Web研の使い方・学び方

Webにおいては「作って学ぶ」ということが大切です。Webは少なくとも3言語（マークアップ含む）を扱う分野で、いちいち文法から始めるとその量に圧倒され簡単に挫折してしまいます。
そのため、「人のコードをコピペ（真似）して動かす」や「動いたらそれを拡張してみる」というように、うまく一回に学ぶ量を減らしつつ必要になったら調べる形で進めると良いです。
Web研では講習会を通してサンプルアプリケーション作りを学び、そのアプリケーションをベースとして拡張する形で学ぶと動かしながら、遊びながら勉強できて本当に楽です！

また、Webを学習するにあたってわからないことがあったら、まずは自分で調べてみましょう。自分で調べることで、なにがわからないのか自分で把握することができたり、調べようと思ったこと以上に知識を得ることができたり、調べる力がつくのではないかと思います。
```

2024-04-20 16:22 UTC, sor4chi commented on blog/2024/webken/1.md
> +Webの技術のベースとなるのはやはり「通信」です。
追加したい

**リクエスト**という「データをください！」という要求操作と**レスポンス**という「ほらやるよ！」という応答操作でやり取りが行われます。

2024-04-20 16:50 UTC, batora9 commented on blog/2024/webken/1.md
> +Web研は年間を通して主にフロントエンド・バックエンド・デザインの講義を行います。Webについて初心者の方も、経験者の方も講義＋各自の事後学習である程度の基礎的な知識や技術を身に着けることができると思います。また、Webを学習するにあたってわからないことがあったら、まずは自分で調べてみましょう。自分で調べることで、なにがわからないのか自分で把握することができたり、調べようと思ったこと以上に知識を
Web研の使い方・学び方これもねらいの一つなのでまとめちゃいます

2024-04-20 17:28 UTC, sor4chi requested changes

2024-04-20 17:28 UTC, sor4chi commented on blog/2024/webken/1.md
> +また、Webを学習するにあたってわからないことがあったら、まずは自分で調べてみましょう。自分で調べることで、なにがわからないのか自分で把握することができたり、調べようと思ったこと以上に知識を得ることができたり、調べる力がつくのではないかと思います。
段落分けたりしてなるべく圧減らしたさある

2024-04-20 17:30 UTC, batora9 commented on blog/2024/webken/1.md
> +また、Webを学習するにあたってわからないことがあったら、まずは自分で調べてみましょう。自分で調べることで、なにがわからないのか自分で把握することができたり、調べようと思ったこと以上に知識を得ることができたり、調べる力がつくのではないかと思います。
Done

2024-04-20 22:23 UTC, a01sa01to commented on blog/2024/webken/1.md
> +クライアントとはユーザーが直接触る部分のことで厳密には、HTTP リクエストを送る側 (具体例として Web ブラウザやスマホアプリ)などを指します。
```suggestion
クライアントとは、ユーザーが直接触る部分 (より厳密にはユーザーが触る部分に限らず HTTP リクエストを送る側) のことで、具体例として Web ブラウザやスマホアプリなどを指します。
```
こうかなぁ

2024-04-20 22:23 UTC, a01sa01to commented on blog/2024/webken/1.md
> +実際にChromeだと検証から、他のブラウザでもDeveloper Toolsから実際に今表示されているサイトのHTMLを見ることができます。
```suggestion
実際にChromeだと「検証」から、他のブラウザでも「Developer Tools」から実際に今表示されているサイトのHTMLを見ることができます。
```
このほうがわかりやすそう

2024-04-22 04:05 UTC, a01sa01to submitted a review, later dismissed

2024-04-22 04:26 UTC, sor4chi approved these changes

2024-04-22 04:26 UTC, sor4chi commented
あれ、辻くん図作ってなかったっけ

2024-04-22 04:46 UTC, yukikamome316 requested changes
作ったので差し替えてください！

2024-04-22 04:46 UTC, yukikamome316 commented on public/images/blog/2024/webken-1/html-structure-1.png
![image](https://github.com/saitamau-maximum/blog/assets/32415464/71a9a4f5-861d-4b15-8214-6fcbca030eb7)

2024-04-22 04:46 UTC, yukikamome316 commented on public/images/blog/2024/webken-1/html-structure-2.png
![image](https://github.com/saitamau-maximum/blog/assets/32415464/664229dc-2b4d-4627-b299-25898e76bf62)

2024-04-22 05:06 UTC, a01sa01to submitted a review, later dismissed

2024-04-22 05:11 UTC, sor4chi requested changes

2024-04-22 05:11 UTC, sor4chi commented on public/images/blog/2024/webken-1/html-structure-2.png
![Screenshot 2024-04-22 at 14 10 08](https://github.com/saitamau-maximum/blog/assets/80559385/b1b8c714-26e9-4cfc-9f94-bc49e47fb7a7)
こっちの方がノードが分かれてることが理解しやすそうなので置き換えて欲しい！

2024-04-22 05:21 UTC, a01sa01to approved these changes

2024-04-22 05:21 UTC, sor4chi approved these changes

2024-04-22 06:55 UTC, yukikamome316 approved these changes
ありがとーー

2024-04-22 06:57 UTC, merged