fix: blogのLinkMetaのedge fetching化と開発者体験の向上
saitamau-maximum/blog pull request #75
Opened 2024-04-25 06:08 UTC by sor4chi

2024-04-25 06:11 UTC, hana-rs approved these changes

2024-04-25 08:16 UTC, a01sa01to requested changes

2024-04-25 08:16 UTC, a01sa01to commented on src/app/blog/[...slug]/page.tsx
> +    // キャッシュが存在しない場合は何もしない
コメントミスってそう

2024-04-25 08:16 UTC, a01sa01to commented on src/components/blog/link-card/link-card.tsx
> +    console.log('href', href);
消さなくてよい？

2024-04-25 08:16 UTC, a01sa01to commented on src/constants/url.ts
> +  OGP_FETCHER_ORIGIN: 'https://ogp-fetcher.maximum.vc',
ん、サブドメイン設定したのか

2024-04-25 09:57 UTC, sor4chi commented
@a01sa01to 
PCさわれないので直してマージして

2024-04-26 07:08 UTC, sor4chi commented on src/constants/url.ts
> +  OGP_FETCHER_ORIGIN: 'https://ogp-fetcher.maximum.vc',
え、言ってなかったっけw
勝手にやったわ

2024-04-26 07:43 UTC, a01sa01to approved these changes

2024-04-26 11:40 UTC, sor4chi commented
@hana-rs 二人以上のApproveが必要なのでお願いします！

2024-04-26 15:23 UTC, merged