入門講習会第２回
saitamau-maximum/blog pull request #76
Opened 2024-04-25 10:29 UTC by LLstream

2024-04-26 05:52 UTC, LLstream commented
なんだこれ？

2024-04-30 05:44 UTC, LLstream commented
多次元配列についてまで書くか悩んでマウス

2024-04-30 06:00 UTC, a01sa01to requested changes
細かいフォーマットがメインだけどお願いします :pray:
インデント幅もスペース x2 で統一したい :bow:

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +title: "【第2回】はじめての競技プログラミング"
タイトル前回と同じだけどそのままで OK？

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +prev: "./1"
1 のほうに `next: "./2"` を追加してほしい！

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +関数はc++で元から用意されているSTLの関数を利用する方法と、関数を自作して使う方法があります。
```suggestion
関数はC++で元から用意されているSTLの関数を利用する方法と、関数を自作して使う方法があります。
```
基本的には C++ (大文字) で！ (ほかの場所も)

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +| `swap(a,b)`                       | 変数 a と変数 b の値を交換する                          |
```suggestion
| `min(a, b)`                       | a, b のうち小さい方の値を返す                         |
| `max(a, b)`                       | a, b のうち大きい方の値を返す                         |
| `abs(a)`                          | a の絶対値を返す                                      |
| `swap(a, b)                       | 変数 a と変数 b の値を交換する                          |
```
細かいけどフォーマット

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +}
```suggestion
int main() {
    int a = -1, b = 2;
    cout << min(a, b) << endl;           // -1
    cout << max(a, b) << endl;           // 2
    cout << abs(a) << endl;             // 1
    cout << a << " " << b << endl;      // -1 2
    swap(a, b);                          
    cout << a << " " << b << endl;      // 2 -1
    
    vector<int> vec = { 3, 2, 5, 1, 4 };
    for (int i = 0; i < 5; i++) {
        cout << vec.at(i) << " ";       // 3 2 5 1 4
    }
    cout << endl;

    sort(vec.begin(), vec.end());
    for (int i = 0; i < 5; i++) {
        cout << vec.at(i) << " ";       // 1 2 3 4 5
    }
    cout << endl;

    reverse(vec.begin(), vec.end());
    for (int i = 0; i < 5; i++) {
        cout << vec.at(i) << " ";       // 5 4 3 2 1
    }
    cout << endl;
}
```
`,`, `=` などの演算子系の前後に空白を入れると読みやすくなります！

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +}
```suggestion
#include <bits/stdc++.h>
using namespace std;

int main() {
    int a, b, c;
    cin >> a >> b >> c;
    // 引数が2つと決まっているため max(a, b, c) のような書き方はできません
    int ans = max(a, max(b, c)) - min(a, min(b, c));
    // こういった書き方もできます
    // int ans = max({ a, b, c }) - min({ a, b, c });
    cout << ans << endl;
}
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +- 関数に渡された引数を変化させるためには参照渡しを行う必要があります。
```suggestion
- コピーして関数に渡すことを「値渡し」と言います。
- 関数に渡された引数を変化させるためには「参照渡し」を行う必要があります。
```
初出単語は鍵括弧で囲ってあげるといいかも

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +}
```suggestion
// 引数として a, b を受け取り、足した結果となるint型の数値を返す関数
int sum(int a, int b) {
    return a + b;
}

// a と b を入れ替える関数
void Swap(int a, int b) {
    int temp = a;
    a = b;
    b = temp;
}

int main() {
    int a = 1, b = 2;
    cout << sum(a, b) << endl;           // 3

    cout << a << " " << b << endl;      // 1 2
    Swap(a, b);
    cout << a << " " << b << endl;      // 1 2
}
```
関数の説明となるコメントは、関数定義の前がいいかもです

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +}
```suggestion
void Swap(int &a, int &b){  // 参照渡し
    int temp = a;
    a = b;
    b = temp;
}

int main() {
    int a = 1, b = 2;
    cout << a << " " << b << endl;      // 1 2
    Swap(a, b);
    cout << a << " " << b << endl;      // 2 1
}
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +  return ans;
```suggestion
  int ans = 0;
  for (int i = 0; i < scores.size(); i++) {
    ans += scores.at(i);
  }
  return ans;
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +  cout << sum_a*sum_b*sum_c << endl;
```suggestion
  cout << sum_a * sum_b * sum_c << endl;
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    for(int x:vec){
```suggestion
    vector<int> vec = { 1, 2, 3, 4, 5 };
    for (int x : vec) {
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +        int x=vec.at(i);
```suggestion
    vector<int> vec = { 1, 2, 3, 4, 5 };
    for (int i = 0; i < vec.size(); i++) {
        int x = vec.at(i);
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +#define rep(i,n)for(int i=0;i<(n);i++)
```suggestion
#define rep(i, n) for (int i = 0; i < (n); i++)
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +}
```suggestion
#define rep(i, n) for (int i = 0; i < (n); i++)  // ここに追加

int main() {
    vector<int> vec = { 1, 2, 3, 4, 5 };
    rep(i, vec.size()) {
        vec.at(i)++;
        cout << vec.at(i) << " ";
    }
}
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +for文など書く量が多く、面倒なものを先に設定しておくことで楽に書くことができます。
コンパイル時に自動的に置き換えてくれるみたいなことを書いてもよさそう

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +<https://atcoder.jp/contests/apg4b/tasks/APG4b_cg>
```suggestion
範囲for文やマクロを使った解き方や使わない解き方など、いろいろと考えてみてください。

<https://atcoder.jp/contests/apg4b/tasks/APG4b_cg>
```
![image](https://github.com/saitamau-maximum/blog/assets/26807394/ccb1fc58-6fc1-450e-a62f-6e3ba65a0366)

リンクカードが動いてなさそう

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    }
```suggestion
    for (int i = 0; i < 5; i++) {
        cin >> a.at(i);
    }
    for (int i = 0; i < 4; i++) {
        if (a.at(i) == a.at(i + 1)) {
            cout << "YES" << endl;
            return 0;
        }
    }
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    cout << "NO" << endl;
```suggestion
    for (int &x : a) {
        cin >> x;
    }
    for (int i = 0; i < 4; i++) {
        if (a.at(i) == a.at(i + 1)) {
            cout << "YES" << endl;
            return 0;
        }
    }
    cout << "NO" << endl;
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +}
```suggestion
#define rep(i, n) for (int i = 0; i < (n); i++)

int main() {
    vector<int> a(5);
    rep(i, 5) {
        cin >> a.at(i);
    }
    rep(i, 4) {
        if (a.at(i) == a.at(i + 1)) {
            cout << "YES" << endl;
            return 0;
        }
    }
    cout << "NO" << endl;
}
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    }
```suggestion
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << "i:" << i << ",j:" << j << endl;
        }
    }
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +<https://atcoder.jp/contests/apg4b/tasks/APG4b_cf>
```suggestion
2重for文を使います。for文の中の変数が被らないように気を付けましょう。

<https://atcoder.jp/contests/apg4b/tasks/APG4b_cf>
```

2024-04-30 06:00 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    cout << count << endl;
```suggestion
    int n, s;
    cin >> n >> s;
    vector<int> a(n);
    for (int i = 0; i < n; i++) {
        cin >> a.at(i);
    }
    vector<int> p(n);
    for (int i = 0; i < n; i++) {
        cin >> p.at(i);
    }
    int count = 0;
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            if (a.at(i) + p.at(j) == s) {
                count++;
            }
        }
    }
    cout << count << endl;
```

2024-04-30 07:27 UTC, yukikamome316 requested changes

2024-04-30 07:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +}
```suggestion
#include <bits/stdc++.h>
using namespace std;
#define rep(i,n) for (int i = 0; i < (int)(n); i++)  // ここに追加

int main() {
    vector<int> vec = {1, 2, 3, 4, 5};
    rep(i, vec.size()){
        vec.at(i)++;
        cout << vec.at(i) << " ";
    }
}
```

2024-04-30 07:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +}
```suggestion
#include <bits/stdc++.h>
using namespace std;

int main() {
    vector<int> a(5);
    for (int i = 0; i < 5; i++) {
        cin >> a.at(i);
    }
    for (int i = 0; i < 4; i++) {
        if (a.at(i) == a.at(i+1)) {
            cout << "YES" << endl;
            return 0;
        }
    }
    cout << "NO" << endl;
}
```

2024-04-30 07:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +}
```suggestion
#include <bits/stdc++.h>
using namespace std;

int main() {
    vector<int> a(5);
    for (int &x : a) {
        cin >> x;
    }
    for (int i = 0; i < 4; i++) {
        if (a.at(i) == a.at(i+1)) {
            cout << "YES" << endl;
            return 0;
        }
    }
    cout << "NO" << endl;
}
```

2024-04-30 07:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +}
```suggestion
#include <bits/stdc++.h>
using namespace std;
#define rep(i, n) for (int i = 0; i < (int)(n); i++)

int main() {
    vector<int> a(5);
    rep(i, 5) {
        cin >> a.at(i);
    }
    rep(i, 4) {
        if (a.at(i) == a.at(i+1)) {
            cout << "YES" << endl;
            return 0;
        }
    }
    cout << "NO" << endl;
}
```

2024-04-30 07:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +}
```suggestion
#include <bits/stdc++.h>
using namespace std;

int main() {
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << "i:" << i << ",j:" << j << endl;
        }
    }
}
```

2024-04-30 07:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +}
```suggestion
#include <bits/stdc++.h>
using namespace std;

int main() {
    int n, s;
    cin >> n >> s;
    vector<int> a(n);
    for(int i = 0; i < n; i++) {
        cin >> a.at(i);
    }
    vector<int> p(n);
    for (int i = 0;i < n; i++) {
        cin >> p.at(i);
    }
    int count = 0;
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            if (a.at(i) + p.at(j) == s) {
                count++;
            }
        }
    }
    cout << count << endl;
}
```

2024-04-30 07:28 UTC, yukikamome316 commented
レビュー被ってたらすみません

2024-04-30 07:32 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    int a = -1,b = 2;
```suggestion
    int a = -1, b = 2;
```

2024-04-30 07:32 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    vector<int> vec = { 3 , 2 , 5 , 1 , 4 };
```suggestion
    vector<int> vec = { 3, 2, 5, 1, 4 };
```

2024-04-30 07:32 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    //引数が2つのと決まっているため max(a, b, c) のような書き方はできません
```suggestion
    // 引数が2つと決まっているため max(a, b, c) のような書き方はできません
```

2024-04-30 07:32 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    vector<int> vec = { 1, 2, 3, 4, 5};
```suggestion
    vector<int> vec = { 1, 2, 3, 4, 5 };
```

2024-04-30 07:32 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +また、配列だけでなく`string型`でも書くことができます。
```suggestion
また、配列だけでなく`string`型でも書くことができます。
```

2024-04-30 07:32 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +    int count=0;
```suggestion
    int count = 0;
```

2024-04-30 08:01 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +２次元配列を出力する際、２重for文を使います。
```suggestion
2次元配列を出力する際、2重for文を使います。
```

2024-04-30 08:01 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +        result.at(b.at(i) - 1).at(a.at(i) - 1)='x';
```suggestion
        result.at(a.at(i) - 1).at(b.at(i) - 1) = 'o';
        result.at(b.at(i) - 1).at(a.at(i) - 1) = 'x';
```

2024-04-30 08:01 UTC, a01sa01to commented on blog/2024/intro-course/2.md
> +        for (int j = 0; j < n;j++) {
```suggestion
        for (int j = 0; j < n; j++) {
```

2024-04-30 08:15 UTC, a01sa01to commented on package-lock.json
これ消せる？

2024-04-30 08:18 UTC, a01sa01to submitted a review, later dismissed

2024-04-30 08:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +#define rep(i, n) for (int i = 0; i < (n); i++)
```suggestion
#define rep(i, n) for (int i = 0; i < (int)(n); i++)
```

さっきレビューしたけど、警告を消すためにintにキャストすべきかも？

2024-04-30 08:27 UTC, yukikamome316 commented on blog/2024/intro-course/2.md
> +#define rep(i, n) for (int i = 0; i < (n); i++) // ここに追加
他のrepにも同様にキャストをしてほしい(任意)

2024-04-30 08:38 UTC, a01sa01to approved these changes

2024-04-30 08:38 UTC, merged