web研第3回講習会
saitamau-maximum/blog pull request #79
Opened 2024-05-10 19:01 UTC by batora9

2024-05-10 19:55 UTC, sor4chi commented
入門講習会の方の変更が含まれてしまっているので
git fetch origin
git pull --rebase origin main
git push -f origin HEAD
して更新してください！

2024-05-11 03:36 UTC, a01sa01to commented on blog/2024/webken/3.md
> +オブジェクトに特定のプロパティが存在するかどうかを確認するには、`in`演算子を使います。
`in`  でもいいけど `hasOwnProperty` もあるといいかも

2024-05-11 03:36 UTC, a01sa01to commented on blog/2024/webken/3.md
> +document.addEventListener('DOMContentLoaded', onLoaded);
「ページ読み込み完了時」は `load` じゃないかな (`DOMContentLoaded` は CSS とか画像とかの読み込みが完了しているとも限らないので)

2024-05-11 03:36 UTC, a01sa01to commented on blog/2024/webken/3.md
> +document.addEventListener('DOMContentLoaded', onLoaded);
でも下に書いてるのか

2024-05-11 03:36 UTC, a01sa01to commented on blog/2024/webken/3.md
> +`DOMContentLoaded` イベントは、HTMLドキュメントの読み込みが完了したときに発生します。`DOMContentLoaded` イベントが発生するまで、JavaScriptの処理は実行されません。そのため、`DOMContentLoaded` イベントを使って、ページの読み込みが完了したときに処理を実行するようにすると、ページの読み込みが完了する前にJavaScriptの処理が
> JavaScript の処理が実行されることを防ぐことができます

すると何がうれしい？を書いてあげるとよさそう

2024-05-11 13:19 UTC, sor4chi requested changes

2024-05-11 13:19 UTC, sor4chi commented on blog/2024/webken/3.md
> +description: ""
書いて欲しい！

2024-05-11 13:19 UTC, sor4chi commented on blog/2024/webken/3.md
> +作業ディレクトリは前回のものを使用してください。
めんどくさいけど説明するか前回のパーマリンク（id付きリンク）を貼ってあげた方がいいかも

2024-05-11 13:19 UTC, sor4chi commented on blog/2024/webken/3.md
> +オブジェクトに特定のプロパティが存在するかどうかを確認するには、`in`演算子を使います。
講義では厳密性よりも簡潔性を求めたいので`in`でいい気がする
というか`hasOwnProperty`で判断するのはオブジェクトに対してはいいけどクラスに対して応用が効かないのであんまりお勧めできない

ライブラリ内ならあえてhasOwnProperty使うことあるけど

2024-05-11 13:19 UTC, sor4chi commented on blog/2024/webken/3.md
> +
`[要素].style`にはcssをjsで操作できるインターフェースがあります。
`[要素].style.[プロパティ名]`で任意のスタイルを取得したり更新したりすることができます。

2024-05-11 13:19 UTC, sor4chi commented on blog/2024/webken/3.md
> +`DOMContentLoaded` イベントは、HTMLドキュメントの読み込みが完了したときに発生します。`DOMContentLoaded` イベントが発生するまで、JavaScriptの処理は実行されません。そのため、`DOMContentLoaded` イベントを使って、ページの読み込みが完了したときに処理を実行するようにすると、ページの読み込みが完了する前にJavaScriptの処理が
ブラウザはダウンロードしてきたHTMLを上から順に処理していくため、scriptがheadで読み込まれているとbodyの描画を処理する前にscriptが起動してしまうみたいな話書くととてもいいかもしれない

2024-05-11 13:19 UTC, sor4chi commented on blog/2024/webken/3.md
> +
もしできたらtimesとかで自慢してくれるととても嬉しいです見たいなこと書いとくといいかも？

2024-05-11 13:19 UTC, sor4chi commented on blog/2024/webken/3.md
> +
- サイトをデプロイして世界中に公開してみる（発展編）

2024-05-11 17:34 UTC, batora9 commented on blog/2024/webken/3.md
> +description: ""
忘れてました...

2024-05-12 03:11 UTC, a01sa01to commented on blog/2024/webken/3.md
> +オブジェクトに特定のプロパティが存在するかどうかを確認するには、`in`演算子を使います。
まあ補足としてあってもいいんじゃないかなぁ

2024-05-12 03:23 UTC, a01sa01to commented on blog/2024/webken/3.md
> +`DOMContentLoaded` イベントは、HTMLドキュメントの読み込みが完了したときに発生します。`DOMContentLoaded` イベントが発生するまで、JavaScriptの処理は実行されません。そのため、`DOMContentLoaded` イベントを使って、ページの読み込みが完了したときに処理を実行するようにすると、ページの読み込みが完了する前にJavaScriptの処理が
```suggestion
`DOMContentLoaded` イベントは、HTMLドキュメントの読み込みが完了したときに発生します。
`DOMContentLoaded` イベントが発生するまで、`addEventListener` 内に記述したJavaScriptの処理は実行されません。
ブラウザはダウンロードしてきたHTMLを上から順に処理していくため、`script`が`<head>`で読み込まれていると、`<body>`の描画を処理する前に`script`が起動してしまうことになります。
このとき、処理をそのまま行うと、まだ描画の処理がされていない要素を参照してしまうことになり、正しい処理ができません。
そのため、ページの読み込みが完了する前にこういったJavaScriptの処理が実行されることを防ぐことで、正しく要素への操作が行われるようにしています。
```
みたいな感じかな
(レビューしづらいのでいい感じに改行してもらえると助かる)

2024-05-12 03:37 UTC, sor4chi commented on blog/2024/webken/3.md
> +オブジェクトに特定のプロパティが存在するかどうかを確認するには、`in`演算子を使います。
余計なこと教えたくない...
`in`でダメな理由がわからん

2024-05-12 03:50 UTC, a01sa01to commented on blog/2024/webken/3.md
> +オブジェクトに特定のプロパティが存在するかどうかを確認するには、`in`演算子を使います。
知識としてあってもいいかなって思ったけど余計な事だと思うならいいや

2024-05-12 05:30 UTC, yukikamome316 approved these changes

2024-05-12 13:05 UTC, a01sa01to commented on blog/2024/webken/3.md
> +`[要素].style`にはcssをjsで操作できるインターフェースがあります。
```suggestion
`[要素].style`にはcssをjsから操作できるインターフェースがあります。
```

2024-05-12 13:05 UTC, a01sa01to commented on blog/2024/webken/3.md
> +### なぜDOMContentLoadedイベントを使うのか
Tip だったら見出しじゃなくて details でもいいかも (おまかせする)

2024-05-12 15:42 UTC, a01sa01to approved these changes

2024-05-12 16:38 UTC, sor4chi approved these changes

2024-05-13 04:04 UTC, merged