docs(intro-course):【第4回】便利なデータ構造
saitamau-maximum/blog pull request #8
Opened 2023-05-15 18:00 UTC by takashin9

2023-05-15 23:39 UTC, a01sa01to requested changes

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +`map<Key, Value> 変数名;`
「Keyの型, Valueの型」にしたほうがよさそう？

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +- `priority_queue`を用いると，追加した値のうち大きい順に取り出す処理ができる
大きい順を太字にしたい

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +例
ここだけ例があるのなぜ…？

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +      cnt[x] = 1;
at か [] どっちかで統一したい

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +`priority_queue<型, vector<型>, greater<型>> 変数名;`
例題がほしい (さすがに dijkstra は難しいけど queue で BFS 扱ってるから許されそう…？)

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +| 先頭の要素へのアクセス | `d.front()`<br>`d.back()`<br>`d.at(i)`        | $O(1)$ |
先頭以外もあります…

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +| 先頭の要素を削除       | `d.pop_back()`<br>`d.pop_front()`             | $O(1)$ |
先頭以外もあります…

2023-05-15 23:39 UTC, a01sa01to commented on blog/intro-course-4.md
> +## まとめ
まとめの分量はもっと減らしていいかも (各データ構造ごとに2-3文くらいで、メソッドとか計算量とかの表はなくても良いと思う)

2023-05-16 02:21 UTC, kasa021 commented on blog/intro-course-4.md
> +`priority_queue<型, vector<型>, greater<型>> 変数名;`
https://atcoder.jp/contests/abc234/tasks/abc234_d
この問題とかいいんじゃない

2023-05-16 02:39 UTC, yukikamome316 submitted a review, later dismissed

2023-05-16 02:49 UTC, takashin9 commented on blog/intro-course-4.md
> +`priority_queue<型, vector<型>, greater<型>> 変数名;`
いいかも．ほんとはAOJのALDS1とかがいいかなと思ったけどまだ登録とかしてもらってないよね？

2023-05-16 03:41 UTC, a01sa01to commented on blog/intro-course-4.md
> +`priority_queue<型, vector<型>, greater<型>> 変数名;`
この機会に AOJ 登録してもらうのもあり (実践で使うことになるかもなので...)

2023-05-16 04:06 UTC, takashin9 commented on blog/intro-course-4.md
> +`priority_queue<型, vector<型>, greater<型>> 変数名;`
じゃあAOJの登録の部分の追加と，priority_queueの例題にAOJの問題を追加するのをやろうと思います．
kasaさんも問題探してくれてありがとう．

2023-05-16 08:00 UTC, a01sa01to approved these changes
LGTM!

2023-05-16 08:00 UTC, merged