第四回入門講習会の資料の作成
saitamau-maximum/blog pull request #83
Opened 2024-05-19 19:42 UTC by kazu-8

2024-05-19 20:54 UTC, batora9 requested changes
細かいけどコード内の文字や文字列なので「`」で囲もう

2024-05-19 20:54 UTC, batora9 commented on blog/2024/intro-course/3.md
> +- `while`文の中で、配列dにnを10で割った余りを追加し、nを10で割ろう
```suggestion
- `while`文の中で、配列`d`に`n`を10で割った余りを追加し、`n`を10で割ろう
```

2024-05-19 20:54 UTC, batora9 commented on blog/2024/intro-course/3.md
> +- 配列外参照に気を付けながら、配列dの前後を見比べよう
```suggestion
- 配列外参照に気を付けながら、配列`d`の前後を見比べよう
```

2024-05-19 20:54 UTC, batora9 commented on blog/2024/intro-course/3.md
> +- *(a.begin()+i) と a[i] は同じ
```suggestion
- `*(a.begin()+i)` と `a[i]` は同じ
```

2024-05-20 02:48 UTC, a01sa01to requested changes
フォーマットがメイン
括弧前後とか演算子前後とかにスペースを入れると読みやすくなります！

2024-05-20 02:48 UTC, a01sa01to commented on pnpm-lock.yaml
このファイル戻してもらえると :pray:

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    vector<int> A = { 1, 2, 3, 4, 5 };

    auto itr = A.begin();
    cout << *itr << endl;  // 1

    // インクリメントして次の要素を参照
    itr++;
    cout << *itr << endl;  // 2

    // A[2]と同じ使い方もできる
    cout << *(A.begin() + 2) << endl;  // 3

    // A.end()は配列の最後の要素の "次" を示す
    itr = A.end();

    // デクリメントして最後の要素を参照させる
    itr--;
    cout << *itr << endl;  // 5
}
```
フォーマット

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    vector<int> a(10);
    for (int i = 0; i < 10; i++) {
        // (1)
    }

    int num = 0;                // numは、画面に表示される数字
    auto itr = a.begin();       // itrは、ボタンを押して変わった後の要素のイテレータ
    for (int i = 0; i < 3; i++) {
        // (2)
        // (3)
    }

    // (4)

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
```cpp{7,12,15}
#include <bits/stdc++.h>
using namespace std;

int main() {
    vector<int> a(10);
    for (int i = 0; i < 10; i++) {
        cin >> a[i];
    }

    int num = 0;                // numは画面に表示される数字
    for (int i = 0; i < 3; i++) {
        num = a[num];
    }

    cout << num << endl;

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
```cpp{7,13,14,17}
#include <bits/stdc++.h>
using namespace std;

int main() {
    vector<int> a(10);
    for (int i = 0; i < 10; i++) {
        cin >> *(a.begin() + i);
    }

    int num = 0;                // numは画面に表示される数字
    auto itr = a.begin();       // itrはボタンを押したとき変わる要素のイテレータ
    for (int i = 0; i < 3; i++) {
        itr = a.begin() + num;
        num = *itr;
    }

    cout << num << endl;

    return 0;
}
```
言語のところに `{行番号}` とするとハイライトできるので積極的に使おう！
ref: https://blog.maximum.vc/blog/markdown/#codeblock

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +- `map`や`set`などの構造体にはA[i]の形でアクセスできない。
map は `A[i]` の形でアクセスできるはず？

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +| `accumulate(A.begin(), A.end(), x)` | 配列Aの総和を求める                      |
```suggestion
| `sort(A.begin(), A.end())`           | 配列Aの要素を昇順に並び替える            |
| `reverse(A.begin(), A.end())`        | 配列Aの要素を逆にする                    |
| `min_element(A.begin(), A.end())`    | 配列Aの要素の最小値の**イテレータ**を求める |
| `max_element(A.begin(), A.end())`    | 配列Aの要素の最大値の**イテレータ**を求める |
| `accumulate(A.begin(), A.end(), x)` | 配列Aの総和を求める                      |
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
void print(vector<int> vec) {
    for (int now : vec) cout << now << ' ';
    cout << endl;
    return;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +    cout << sum << endl;           // 15
```suggestion
int main() {
    vector<int> A = { 4, 5, 1, 3, 2 };
    print(A);                      // 4 5 1 3 2

    // sortの場合
    sort(A.begin(), A.end());
    print(A);                      // 1 2 3 4 5

    // reverseの場合
    reverse(A.begin(), A.end());
    print(A);                      // 5 4 3 2 1

    // min_elementの場合
    auto min_itr = min_element(A.begin(), A.end());
    cout << *min_itr << endl;      // 1

    // max_elementの場合
    auto max_itr = max_element(A.begin(), A.end());
    cout << *max_itr << endl;      // 5

    // accumulateの場合
    // 第 3 引数に0を入れるとint型になってしまうので、小数や long long 型を扱うときは注意
    int sum = accumulate(A.begin(), A.end(), 0);
    cout << sum << endl;           // 15
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    // 要素がstring型の配列の場合
    vector<string> str = { "apple", "dog", "student", "sun", "game" };

    sort(str.begin(), str.end());
    for (string i : str) cout << i << ' ' ;     // apple dog game student sun
    cout << endl;

    reverse(str.begin(), str.end());
    for (string i : str) cout << i << ' ' ;      // sun student game dog apple
    cout << endl;

    // 文字列の場合
    string s = "maximum";

    sort(s.begin(), s.end());
    cout << s << endl;       // aimmmux

    reverse(s.begin(), s.end());
    cout << s << endl;       // xummmia

    // 大文字、小文字、数字、記号が混ざる場合
    string t = "Oh11ne-Y0ro4ku";

    sort(t.begin(), t.end());  // ASCIIコード表を参照
    cout << t << endl;        // -0114OYehknoru

    reverse(t.begin(), t.end());
    cout << t << endl;       // uronkheYO4110-
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    vector<int> a(3);
    for (int i = 0; i < 3; i++) cin >> a[i];

    // これより下に記述

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    vector<int> a(3);
    for (int i = 0; i < 3; i++) cin >> a[i];

    sort(a.begin(), a.end());

    if (a[2] - a[1] == a[1] - a[0])
        cout << "Yes" << endl;
    else
        cout << "No" << endl;

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    int n;
    cin >> n;
    vector<int> d;  // nを各桁に分解して配列として保存する

    // nが0より大きい間繰り返す
    while (n > 0) {
        // (1)
        // (2)
    }

    // (3)

    for (/* (4) */) {
        if (/* (5) */) {
            // (6) 二行
        }
    }

    // (7)

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +#include <bits/stdc++.h>
```suggestion
#include <bits/stdc++.h>
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +#include <bits/stdc++.h>
```suggestion
#include <bits/stdc++.h>
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +#include <bits/stdc++.h>
```suggestion
#include <bits/stdc++.h>
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +#include <bits/stdc++.h>
```suggestion
#include <bits/stdc++.h>
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +#include <bits/stdc++.h>
```suggestion
#include <bits/stdc++.h>
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    int n;
    cin >> n;
    vector<int> d;  // nを各桁に分解して配列として保存する

    // nが0より大きい時繰り返す
    while (n > 0) {
        d.push_back(n%10); // dの末尾にnを10で割った余りを追加
        n /= 10;  // nを10で割る
    }

    // この時、dにはnを右から見たときの順に入っている。つまり逆
    // 例: n = 321 の時、 d = { 1, 2, 3 }
    reverse(d.begin(), d.end());

    for (int i = 1; i < d.size(); i++) {
        // dの前後を見比べて条件に合うか確かめる
        if (d[i - 1] <= d[i]) {
            cout << "No" << endl;
            return 0;
        }
    }

    cout << "Yes" << endl;

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    string n;
    cin >> n;
    for (int i = 1; i < n.size(); i++) {
        if (n[i - 1] <= n[i]) {
            cout << "No" << endl;
            return 0;
        }
    }
    cout << "Yes" << endl;
    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    vector<int> a(4);
    for (int i = 0; i < 4; i++) cin >> a[i];

    // これより下に記述

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    vector<int> a(4);
    for (int i = 0; i < 4; i++) cin >> a[i];

    int min_num = *min_element(a.begin(), a.end()); //min_elementはイテレータを取得することに注意

    /*
    別解1:
    int min_num = min({ a[0], a[1], a[2], a[3] });
    */

    /*
    別解2:
    int min_num = 100;
    for (int i = 0; i < a.size(); i++)
        if(min_num > a[i])
            min_num = a[i];
    */

    cout << min_num << endl;

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +int main(){
```suggestion
int main() {
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +}
```suggestion
int main() {
    vector<int> vec = { 3, 1, -5, -2, 4 };

    // 昇順にソート
    sort(vec.begin(), vec.end());
    for (int v : vec) cout << v << ' '; // -5 -2 1 3 4
    cout << endl;

    // 絶対値の小さい順にソート
    sort(vec.begin(), vec.end(), [](int i, int j) -> bool {
        return abs(i) < abs(j); // absは引数の絶対値を返す関数
    });
    for (int v : vec) cout << v << ' '; // 1 -2 3 4 -5
    cout << endl;

    return 0;
}
```

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +<https://atcoder.jp/contests/ABC317/tasks/ABC317_B>
```suggestion
<https://atcoder.jp/contests/ABC242/tasks/ABC242_B>

<https://atcoder.jp/contests/ABC253/tasks/ABC253_A>

<https://atcoder.jp/contests/ABC263/tasks/ABC263_A>

<https://atcoder.jp/contests/ABC288/tasks/ABC288_B>

<https://atcoder.jp/contests/ABC291/tasks/ABC291_B>

<https://atcoder.jp/contests/ABC317/tasks/ABC317_B>
```
たぶん改行入れないとリンクカードが正しく表示されない気がする？

2024-05-20 02:48 UTC, a01sa01to commented on blog/2024/intro-course/3.md
> +<https://atcoder.jp/contests/ABC323/tasks/ABC323_B>
```suggestion
<https://atcoder.jp/contests/ABC201/tasks/ABC201_B>

<https://atcoder.jp/contests/ABC213/tasks/ABC213_B>

<https://atcoder.jp/contests/ABC260/tasks/ABC260_B>

<https://atcoder.jp/contests/ABC323/tasks/ABC323_B>
```

2024-05-20 13:28 UTC, yukikamome316 submitted a review, later dismissed

2024-05-20 14:23 UTC, a01sa01to approved these changes

2024-05-20 15:43 UTC, yukikamome316 approved these changes

2024-05-21 01:58 UTC, hana-rs approved these changes

2024-05-21 02:02 UTC, batora9 approved these changes

2024-05-21 02:03 UTC, merged