ヘッダー、prev,next部分を変更
saitamau-maximum/blog pull request #85
Opened 2024-05-27 06:31 UTC by hana-rs

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +| `tie(a, b)=P` | pair型の変数Pの要素をa,bに代入する |
```suggestion
| `tie(a, b) = P` | pair型の変数Pの要素をa, bに代入する |
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +| `pair<型1,型2> P;` | pair型の変数Pを宣言する |
```suggestion
| `pair<型1, 型2> P;` | pair型の変数Pを宣言する |
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +| `pair<型1,型2> P(a, b);` | pair型の変数Pを宣言し、a,bで初期化する |
```suggestion
| `pair<型1, 型2> P(a, b);` | pair型の変数Pを宣言し、a,bで初期化する |
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +`P.first==a;` `P.second==b;`ということになる。
```suggestion
`P.first == a;` `P.second == b;`ということになる。
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +- 型1,型2に入る型は`int`型や`longlong`型、`string`型などなんでも良い。
```suggestion
- 型1、型2に入る型は`int`型や`long long`型、`string`型などなんでも良い。
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +pair<string,string> name;//pair型の変数nameを宣言
```suggestion
pair<string, string> name;  // pair型の変数nameを宣言
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +name.first="Yamada";//nameの1つ目の要素にYamadaを代入
```suggestion
name.first = "Yamada";  // nameの1つ目の要素にYamadaを代入
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +name.second="Taro";//nameの2つ目の要素にTaroを代入
```suggestion
name.second = "Taro";  // nameの2つ目の要素にTaroを代入
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +cout << person.first << " " << person.second << endl; // Yamada 175.5
```suggestion
person = make_pair("Yamada", 175.5);
cout << person.first << " " << person.second << endl;  // Yamada 175.5
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +- pair型のvectorをソートするには、`sort(P.begin(),P.end());`とする。
```suggestion
- pairを配列で持つには、`vector<pair<型1, 型2>> P;`とする。
- 例えば、`vector<pair<int, int>> P;`とすると、`P.at(i).first`でi番目の要素の1つ目の要素にアクセスできる。
- pair型のvectorをソートするには、`sort(P.begin(), P.end());`とする。
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +         { return a.second < b.second; });// ラムダ式ソートでab.secondが小さい順にソート
```suggestion
         { return a.second < b.second; });  // ラムダ式ソートでab.secondが小さい順にソート
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +    {
```suggestion
    rep(i, n) {
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +        cout << ab[i].first << " " << ab[i].second << endl;// abを一行ずつ出力
```suggestion
        cout << ab[i].first << " " << ab[i].second << endl;  // abを一行ずつ出力
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +get<3>(P); // これはOK
```suggestion
| `tuple<型1, 型2, ...> P;` | tuple型の変数Pを宣言する |
| `tuple<型1, 型2, ...> P(a,  b, ...);` | tuple型の変数Pを宣言し、a, b, ...で初期化する |
| `get<i>(P)` | tuple型の変数Pのi番目の要素にアクセスする |
| `make_tuple(a, b,...)` | a, b, ...を要素とするtuple型の変数を作成する |
| `tie(a, b,...) = P` | tuple型の変数Pの要素をa, b, ...に代入する |

- ただし、for文を使って`tuple`型の変数の要素にアクセスすることはできない。
- `i`は定数である必要があり、実装時は`0, 1, 2, ...`などの値で書く必要がある。
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +```cpp
```suggestion
tuple<string, string, int> person;
person = make_tuple("Yamada", "Taro", 20);
cout << get<0>(person) << " " << get<1>(person) << " " << get<2>(person) << endl;  // Yamada Taro 20
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +<https://atcoder.jp/contests/abc128/tasks/abc128_b>
```suggestion
tuple<int> a(0);
tuple<int, int> b(1, 2);
cout << get<0>(a) << endl; // 0
cout << get<0>(b) << " " << get<1>(b) << endl;  // 1 2
```

2024-05-27 18:29 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +auto [x, y] = a;
```suggestion
- いちいち`x = a.first`, `y = a.second`, `z = get<0>(b)`みたいに書くことは面倒。
```

2024-05-27 18:39 UTC, yukikamome316 commented on blog/2024/intro-course/4.md
> +        cout << ab[i].first << " " << ab[i].second << endl; // abを一行ずつ出力
```suggestion
    rep(i, n) {
```

2024-05-28 00:31 UTC, batora9 commented
まず`git pull origin main`しておこう

2024-05-28 00:40 UTC, batora9 requested changes

2024-05-28 00:40 UTC, batora9 commented on blog/2024/intro-course/4.md
> +- 型1、型2に入る型は`int`型や`longlong`型、`string`型などなんでも良い。
```suggestion
- 型1、型2に入る型は`int`型や`long long`型、`string`型などなんでも良い。
```

2024-05-28 00:40 UTC, batora9 commented on blog/2024/intro-course/4.md
> +| `tie(a, b, ...)=P` | tuple型の変数Pの要素をa, b, ...に代入する |
```suggestion
| `tie(a, b, ...) = P` | tuple型の変数Pの要素をa, b, ...に代入する |
```

2024-05-28 01:17 UTC, a01sa01to requested changes

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +`P.first == a;` `P.second == b;`ということになる。
```suggestion
`P.first == a`, `P.second == b`ということになる。
```
「等しい」ってことを言いたいなら `;` はいらないかな

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +}
```suggestion
int main() {
    int n;
    cin >> n;
    vector<pair<int, int>> ab(n);
    rep(i, n) {
        int a, b;
        cin >> a >> b;
        ab[i] = { a, b };
    }

    sort(ab.begin(), ab.end(), [](pair<int, int> a, pair<int, int> b) {
        return a.second < b.second;  // ラムダ式ソートでab.secondが小さい順にソート
    });

    rep(i, n) {
        cout << ab[i].first << " " << ab[i].second << endl; // abを一行ずつ出力
    }
}
```
フォーマット

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +}
```suggestion
int main() {
    int n;
    cin >> n;
    vector<tuple<string, int, int>> abc(n);
    rep(i, n) {
        string a;
        int b;
        cin >> a >> b;
        abc[i] = { a, b, i+1 };
    }
    // 1番目の値でソート、同じなら2番目の値が大きい順でソート
    sort(abc.begin(), abc.end(), [](tuple<string, int, int> a, tuple<string, int, int> b) {
        if (get<0>(a) == get<0>(b)) {
            return get<1>(a) > get<1>(b);
        }
        else {
            return get<0>(a) < get<0>(b);
        }
    });

    // 3番目の値を出力
    rep(i, n) {
        cout << get<2>(abc[i]) << endl;
    }
}
```

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +- **分割代入**を使うと楽に書くことができる。
「分割代入」は JS かな、 C++ だと「構造化束縛」

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +```cpp
ここ消しちゃってつなげてもいい気がする

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +```cpp
こっちも

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +//これは以下の文と同じ
```suggestion
// これは以下の文と同じ
```

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +//これは以下の文と同じ
```suggestion
// これは以下の文と同じ
```

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +#### 分割代入で`auto[x, y] = a`と書いた、`auto`とは？
```suggestion
#### 構造化束縛で`auto [x, y] = a`と書いた、`auto`とは？
```

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +- `using <別名> = <元の型>;` を　`using namespace std;` の後に書く。
```suggestion
- `using <別名> = <元の型>;` を `using namespace std;` の後に書く。
```

2024-05-28 01:17 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +- `using <別名> = <元の型>;` を　`using namespace std;` の後に書く。
まあ 575 の後である必要はないんだけどね

2024-05-28 01:20 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +  //同じ型に対して別名をつけているので、これも同じになる
```suggestion
  //同じ long long 型に対して別名をつけているので、これも同じになる
```

2024-05-28 01:20 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +- 例えば、vector<vector<vector<vector<int>>>>型を`int4D`という名前で使いたい場合、以下のように書く。
```suggestion
- 例えば、`vector<vector<vector<vector<int>>>>` 型を`int4D`という名前で使いたい場合、以下のように書く。
```
なんか表示がへん？
![image](https://github.com/saitamau-maximum/blog/assets/26807394/e7e3a47d-7133-4fbe-9e8b-9f87ab98fa80)

2024-05-28 02:01 UTC, hana-rs commented on blog/2024/intro-course/4.md
> +- `make_pair(a, b)`は`{a, b}`と同じ意味である。
一緒ではないんですね

2024-05-28 02:07 UTC, hana-rs commented on blog/2024/intro-course/4.md
> +- **分割代入**を使うと楽に書くことができる。
名前が違うだけでやってることは同じだったりするんですか？

2024-05-28 02:12 UTC, hana-rs commented on blog/2024/intro-course/4.md
> +| `pair<型1, 型2> P(a, b);` | pair型の変数Pを宣言し、a,bで初期化する |
tupleの方も直した方がいいですか？

2024-05-28 02:54 UTC, batora9 submitted a review, later dismissed

2024-05-28 03:02 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +- **分割代入**を使うと楽に書くことができる。
- vector には対応してない
- array (要素数固定の配列) なら構造化束縛できるけど、
```js
const [a, b, ...rest] = [1, 2, 3, 4, 5]
// a = 1, b = 2, rest = [3, 4, 5]
```
みたいなことができない
- 実は構造体に対しても構造化束縛できたりする

...って感じで、やってることとしては同じだけど文法の違いがあるかんじかな
ref: https://cpprefjp.github.io/lang/cpp17/structured_bindings.html

2024-05-28 03:06 UTC, batora9 commented
あささんのが終わればOKかな

2024-05-28 03:07 UTC, a01sa01to reviewed
- https://github.com/saitamau-maximum/blog/pull/85#discussion_r1616310509
- https://github.com/saitamau-maximum/blog/pull/85#discussion_r1616311393
- https://github.com/saitamau-maximum/blog/pull/85#discussion_r1616311519
- https://github.com/saitamau-maximum/blog/pull/85#discussion_r1616312090
- https://github.com/saitamau-maximum/blog/pull/85#discussion_r1616312936

こいつら直してもらえれば OK

2024-05-28 03:44 UTC, hana-rs commented on blog/2024/intro-course/4.md
> +- **分割代入**を使うと楽に書くことができる。
なるほど…/(><)\
理解ですありがとうございます

2024-05-28 05:20 UTC, a01sa01to reviewed
余計な空白が含まれちゃってるのでここだけ 🙏

2024-05-28 05:20 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +int main() {
```suggestion
using namespace std;

int main() {
```

2024-05-28 05:20 UTC, a01sa01to commented on blog/2024/intro-course/4.md
> +
```suggestion

  sort(p.begin(), p.end());

```

2024-05-28 07:41 UTC, a01sa01to approved these changes

2024-05-28 07:42 UTC, merged