入門講習会第6回資料
saitamau-maximum/blog pull request #93
Opened 2024-06-28 01:19 UTC by LLstream

2024-07-01 10:48 UTC, a01sa01to requested changes
フォーマットメインです

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    stack<int> s,s1;
```suggestion
    stack<int> s, s1;
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    s1=s;
```suggestion
    s1 = s;
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < q; i++ ) {
```suggestion
    for (int i = 0; i < q; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        if ( a == 1 ) {
```suggestion
        if (a == 1) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        else if ( a == 2 ) {
```suggestion
        else if (a == 2) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        else if ( a == 3 ) {
```suggestion
        else if (a == 3) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +| `s1=s` | stack型の変数`s`をstack型の変数`s1`に代入する | $O(N)$ |
```suggestion
| `s1 = s` | stack型の変数`s`をstack型の変数`s1`に代入する | $O(N)$ |
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +
queue は `q1 = que` ないのか

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < q; i++ ) {
```suggestion
    for (int i = 0; i < q; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        if ( query == 1 ) {
```suggestion
        if (query == 1) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        else if ( query == 2 ) {
```suggestion
        else if (query == 2) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        else if ( query == 3 ) {
```suggestion
        else if (query == 3) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +- 追加した値のうち大きい順に取り出すことができる
大きい順を強調してもいいかも

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +| `priority_queue<型> pq;` | priority_queue型の変数`pq`を宣言する | $O(logN)$ |
```suggestion
| `priority_queue<型> pq;` | priority_queue型の変数`pq`を宣言する | $O(\log N)$ |
```
ほかのところも `logN` は `\log N` にしよう
$logN$ が $\log N$ になります

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < q; i++ ) {
```suggestion
    for (int i = 0; i < q; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        if ( a == 1 ) {
```suggestion
        if (a == 1) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        else if ( a == 2 ) {
```suggestion
        else if (a == 2) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +        else if ( a == 3 ) {
```suggestion
        else if (a == 3) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +- `queue`と`stack`の両方の操作ができる　~~上位互換?~~
「stack の操作もできる」は言い方的に微妙かも
queue が後ろから入れて前から出すのイメージ、 deque が前からでも後ろからでも出し入れできるよっていうニュアンス

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +| `d.at(i),d[i];` | deque型の変数`d`の`i`番目の要素にアクセスする | $O(1)$ |
```suggestion
| `d.at(i)`, `d[i];` | deque型の変数`d`の`i`番目の要素にアクセスする | $O(1)$ |
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +| `d.insert(d.begin()+i,j)` | deque型の変数`d`の`i`番目に`j`を挿入する | $O(1)$ |
```suggestion
| `d.insert(d.begin()+i, j)` | deque型の変数`d`の`i`番目と`i+1`番目の間に`j`を挿入する | $O(N)$ |
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +| `d.clear()` | deque型の変数`d`の中の全ての要素を削除する | $O(1)$ |
```suggestion
| `d.clear()` | deque型の変数`d`の中の全ての要素を削除する | $O(N)$ |
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +- `deque`に数値を入れていってソートして前後n個を削除しましょう
```suggestion
- `deque`に数値を入れていってソートして前後 $n$ 個を削除しましょう
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < 5 * n; i++) {
```suggestion
    for (int i = 0; i < 5 * n; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < n; i++) {
```suggestion
    for (int i = 0; i < n; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < 3 * n; i++) {
```suggestion
    for (int i = 0; i < 3 * n; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    cout << ans / ( 3 * n ) << endl;
```suggestion
    cout << ans / (3 * n) << endl;
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < 5 * n; i++) {
```suggestion
    for (int i = 0; i < 5 * n; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    for ( int i = 0; i < n; i++) {
```suggestion
    for (int i = 0; i < n; i++) {
```

2024-07-01 10:48 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    cout << ans / ( 3 * n ) << endl;
```suggestion
    cout << ans / (3 * n) << endl;
```

2024-07-01 10:54 UTC, LLstream commented on blog/2024/intro-course/6.md
> +
できないと思ってたんですけど、できるんですか

2024-07-01 10:56 UTC, LLstream commented on blog/2024/intro-course/6.md
> +- 追加した値のうち大きい順に取り出すことができる
了解です

2024-07-01 10:59 UTC, LLstream commented on blog/2024/intro-course/6.md
> +- `queue`と`stack`の両方の操作ができる　~~上位互換?~~
たしかにそうですね
前からでも後ろからでも出し入れできるって書きます

2024-07-01 14:46 UTC, LLstream commented on blog/2024/intro-course/6.md
> +
試したらいけました
加筆しときます

2024-07-01 15:24 UTC, LLstream commented on blog/2024/intro-course/6.md
> +
全部で試したらいけたので全部に足しときました

2024-07-02 03:44 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +    cout << s.empty() << endl;  // 1(true)
`cout << boolalpha` としておくことで `true`/`false` と表示されるようになります

2024-07-02 03:44 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +- 追加した値のうち`大きい順`に取り出すことができる
太字がいいかも？

```suggestion
- 追加した値のうち**大きい順**に取り出すことができる
```

2024-07-02 03:44 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +| `priority_queue<型> pq;` | priority_queue型の変数`pq`を宣言する | $O(log N)$ |
```suggestion
| `priority_queue<型> pq;` | priority_queue型の変数`pq`を宣言する | $O(\log N)$ |
```

2024-07-02 03:44 UTC, a01sa01to commented on blog/2024/intro-course/6.md
> +| `pq.pop()` | priority_queue型の変数`pq`中で最大の要素を削除する | $O(log N)$ |
```suggestion
| `pq.pop()` | priority_queue型の変数`pq`中で最大の要素を削除する | $O(\log N)$ |
```

2024-07-02 04:01 UTC, LLstream commented on blog/2024/intro-course/6.md
> +    cout << s.empty() << endl;  // 1(true)
emptyとか真偽判定のやつだけtrue/falseになる感じなんですかね
size()==0の時はそのままだったので

2024-07-02 04:36 UTC, a01sa01to approved these changes

2024-07-02 08:07 UTC, yukikamome316 commented on pnpm-lock.yaml
> +    dev: false
この変更は何？

2024-07-02 08:10 UTC, yukikamome316 approved these changes

2024-07-02 08:15 UTC, merged