第8回web研資料
saitamau-maximum/blog pull request #94
Opened 2024-06-29 16:19 UTC by batora9

2024-06-30 12:06 UTC, yukikamome316 requested changes

2024-06-30 12:06 UTC, yukikamome316 commented on blog/2024/webken/8.md
> +  created_at DATETIME NOT NULL
SQLiteにはDATETIME型の概念がないので、今回はTEXT型として扱おう

> SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values:

https://www.sqlite.org/datatype3.html

https://qiita.com/s_ryota/items/b3a2c48cbecbc3fdb5a5

2024-06-30 12:06 UTC, yukikamome316 commented on blog/2024/webken/8.md
> +データベースには主に**リレーショナルデータベース、NoSQLデータベース、NewSQLデータベース**など様々な種類があり、それぞれ異なる保存形式やパフォーマンス、機能を持っています。 これらを説明し始めるとキリがないので、今回はsqliteというデータベースを使ってデータベースの基本的な操作を学びます。
sqlite -> SQLite
以下同様

2024-06-30 15:14 UTC, a01sa01to requested changes

2024-06-30 15:14 UTC, a01sa01to commented on blog/2024/webken/8.md
> +データベースには主に**リレーショナルデータベース、NoSQLデータベース、NewSQLデータベース**など様々な種類があり、それぞれ異なる保存形式やパフォーマンス、機能を持っています。 これらを説明し始めるとキリがないので、今回はsqliteというデータベースを使ってデータベースの基本的な操作を学びます。
```suggestion
データベースには主に**リレーショナルデータベース**、**NoSQLデータベース**、**NewSQLデータベース**など様々な種類があり、それぞれ異なる保存形式やパフォーマンス、機能を持っています。 これらを説明し始めるとキリがないので、今回はsqliteというデータベースを使ってデータベースの基本的な操作を学びます。
```

概要として誤解を恐れずに書くと

- NoSQL (Not only SQL): RDB 以外の総称
- NewSQL: いいとこどり

みたいなのはあってもいいかも

2024-06-30 15:14 UTC, a01sa01to commented on blog/2024/webken/8.md
> +このような表のことを**テーブル**とも呼びます。テーブルは、**行(レコード)と列(カラム)** で構成されています。
```suggestion
このような表のことを**テーブル**とも呼びます。テーブルは、**行(レコード)**と**列(カラム)** で構成されています。
```

2024-06-30 15:14 UTC, a01sa01to commented on blog/2024/webken/8.md
> +.schema tweets
これは SQLite の書き方であって一般には使えないので一応注意ね

2024-06-30 15:14 UTC, a01sa01to commented on blog/2024/webken/8.md
> +`.show`コマンドを実行すると、データベース接続に関する設定オプションが表示されます。
`.show`, `.headers`, `.mode` とかも SQLite の機能なので

2024-07-01 06:20 UTC, yukikamome316 reviewed
日付の処理の方法を教えるために、
```sql
INSERT INTO tweets (content, user_id, created_at) VALUES ('今日はいい天気ですね', 2, '2024-06-15 12:00:00');
INSERT INTO tweets (content, user_id, created_at) VALUES ('おなかがすいたなー', 3, '2024-06-15 12:30:00');
INSERT INTO tweets (content, user_id, created_at) VALUES ('課題がおわりません', 3, '2024-06-20 13:00:00');
INSERT INTO tweets (content, user_id, created_at) VALUES ('今日のWeb研は何だろう', 1, '2024-06-28 3:30:00');
INSERT INTO tweets (content, user_id, created_at) VALUES ('ICPCがんばるぞ', 2, '2024-07-29 14:00:00');
```
として、今日から過去3日以内の投稿を取得する処理を書かせるといいかも

答えは
```sql
SELECT * FROM tweets
WHERE created_at >= datetime('2024-07-01 19:30:00', '-3 days');
```

2024-07-01 06:30 UTC, a01sa01to commented
https://github.com/saitamau-maximum/blog/pull/94#pullrequestreview-2150513546 これも SQLite の機能なのでそこは注意ね

2024-07-01 08:33 UTC, yukikamome316 submitted a review, later dismissed

2024-07-01 08:36 UTC, a01sa01to commented on blog/2024/webken/8.md
> +今回は、データベースの基礎やSQLiteの文法について学びました。
```suggestion
今回は、データベースの基礎やSQLの文法、SQLiteの機能について学びました。
```
SQL の文法を学ぼう！って話なのでここは SQL の文法でいいんじゃないかな

2024-07-01 08:46 UTC, a01sa01to approved these changes

2024-07-01 08:48 UTC, merged