docs: 計算量に関するブログを作成 (入門講習会)
saitamau-maximum/blog pull request #97
Opened 2024-07-06 15:49 UTC by yukikamome316

## 概要
競プロの計算量についてブログを書きました。7/9(火) の第7回 入門講習会で使用する予定です。

## 変更箇所
- `blog/2024/intro-course/7.md`

## 内容
Asaさんが2022年度に作成した資料の内容に基づいて内容を再構成しました。
計算量に $\log$ が出てくるケースの説明として二分探索とエラトステネスの篩を例に出していますが、今年度は具体的なアルゴリズムまでは載せないで紹介する程度に留めています。

2024-07-07 14:09 UTC, shigekk commented
特に問題無さそうだと思います
「その解法、 TLE しない？」が好きです

2024-07-07 14:12 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +厳密な定義はここでは紹介しませんが、気になる方は調べてみてください。守屋 悦朗さんの『やさしい離散数学』に載っていると思います。
「やさしい離散数学」はあくまで一例 (離散数学の教科書で使っていたから挙げただけ) なので別にこの書籍である必要はないです
```suggestion
厳密な定義はここでは紹介しませんが、気になる方は調べてみてください。情報工学科の「離散数学」で用いられている教科書、守屋 悦朗さんの『やさしい離散数学』にも載っていると思います。
```

2024-07-07 14:12 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +
Tip: 意味的には集合なので、 $O(x) = O(x^2), f = O(x)$ はそれぞれ $O(x) \subseteq O(x^2), f \in O(x)$ みたいな解釈です (知っておくといいかも)

2024-07-07 14:12 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +競技プログラミングでは、底は 2 とみなされるケースもあります ( 二分探索や 2 進数をよく扱う影響かも ？ ) 。
競プロに限らず計算機科学では底は 2 のケースが多いです

2024-07-07 14:12 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +1. $\log_{2} N$
$\log_c N^a$ (適当に数字を入れてもらうとして) のケースもあるといいかも

2024-07-07 14:12 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +また、エラトステネスの篩は素数を求めるアルゴリズムです。ある数 $N$ 以下の素数を全て求めることができ、計算量は $\Omicron(N \log N \log N)$ となります。
```suggestion
また、エラトステネスの篩は素数を求めるアルゴリズムです。ある数 $N$ 以下の素数を全て求めることができ、計算量は $\Omicron(N \log \log N)$ となります。
```
エラトステネスは $\log^2 N$ ではなく $\log \log N$ (つまり $\log (\log N)$ ) です

2024-07-07 14:12 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +アルゴリズムの詳しい説明はここでは割愛しますが、 計算量に $\log$ が出てくるアルゴリズムは **非常に高速** であるということだけでも覚えておいてくださいね！
> $\log$ が出てくるアルゴリズムは **非常に高速** である

ほんとか？ ex: $N^3 \log N$

2024-07-07 14:12 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +$\Omicron$, $\Omega$, $\Theta$ の記法がありますが、競技プログラミングでは $\Omicron$ 記法がよく使われます。
表記上は $O$ がよく使われるが (`O` で書くのが楽、 Mathjax だと `\Omicron` がないなどの影響？)、意味的には $\Theta$ です

2024-07-07 14:34 UTC, hana-rs approved these changes
よみました！未だに計算量ふわふわな自分でも読みやすかったです！

2024-07-08 01:39 UTC, a01sa01to requested changes
7.md はよさそう
6.md の next に 7 を指定してもらえればおっけー

2024-07-08 02:58 UTC, shigekk submitted a review, later dismissed

2024-07-08 02:59 UTC, LLstream submitted a review, later dismissed
わかりやすいと思いました(小並感)

2024-07-08 06:37 UTC, a01sa01to reviewed
ここだけ :pray:

2024-07-08 06:37 UTC, a01sa01to commented on blog/2024/intro-course/7.md
> +| $\Omicron(N \log N)$ | 準線形・線形対数時間    | `std::sort`、 `std::stable_sort`                        |
```suggestion
| $\Omicron(1)$        | 定数時間                | `vector` でのランダムアクセス、 `queue.push` |
| $\Omicron(\log N)$   | 対数時間                | ソート済み配列の二分探索                                |
| $\Omicron(N)$        | 線形時間                | ソートされていない `vector` での値の探索                |
| $\Omicron(N \log N)$ | 準線形・線形対数時間    | `sort`、 `stable_sort`                        |
```
`std::` はなくてもいいかも (`using namespace std` を前提にしているので)

2024-07-08 07:25 UTC, a01sa01to reviewed
表のフォーマットが気になるのでそこだけ直してもらえればいいかも

2024-07-08 08:06 UTC, yukikamome316 commented
> 細かいけど表のフォーマットが気になるのでそこだけ直してもらえればいいかも
フォーマッタに掛けた結果ですが、どうされますか？

2024-07-08 08:13 UTC, a01sa01to commented
> > 細かいけど表のフォーマットが気になるのでそこだけ直してもらえればいいかも
> 
> @a01sa01to フォーマッタに掛けた結果ですが、どうされますか？

...？　フォーマッタにかけるとたぶん `|` の位置がそろわない？
もしかけてもこのままだったらこのままでおっけーです

2024-07-08 08:56 UTC, yukikamome316 commented
> ...？　フォーマッタにかけるとたぶん `|` の位置がそろわない？ もしかけてもこのままだったらこのままでおっけーです

@a01sa01to 
全角文字が含まれているせいか、綺麗に揃わなかったので以下の形式に統一しました
```md
| $\Omicron$ 記法 | 名前 | 使用例 |
| --- | --- | --- |
| $\Omicron(1)$ | 定数時間 | `vector` でのランダムアクセス、 `queue.push` |
| $\Omicron(\log N)$ | 対数時間 | ソート済み配列の二分探索 |
| $\Omicron(N)$ | 線形時間 | ソートされていない `vector` での値の探索 |
| $\Omicron(N \log N)$ | 準線形・線形対数時間 | `sort`、 `stable_sort` |
| $\Omicron(N^2)$ | 二乗時間 | 二重ループ |
| $\Omicron(N^a)$ | 多項式時間 ($a \geq 1$) | 行列計算 ($N^3$) |
| $\Omicron(a^N)$ | 指数時間 ($a \geq 1$) | 愚直な素数探索と因数分解 (良い方法ではない) |
| $\Omicron(N!)$ | 階乗時間 | 順列全探索、 TSP (巡回セールスマン問題) |
```

2024-07-08 09:02 UTC, a01sa01to approved these changes

2024-07-08 10:06 UTC, a01sa01to approved these changes

2024-07-09 06:56 UTC, merged